<?php
/**
 * BudgetDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BudgetDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BudgetDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BudgetDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'financial_year' => 'string',
        'released' => 'bool',
        'released_amount' => 'float',
        'account' => '\OpenAPI\Client\Model\AccountInBudgetDto',
        'subaccount' => '\OpenAPI\Client\Model\SubaccountInBudgetDto',
        'description' => 'string',
        'amount' => 'float',
        'distributed_amount' => 'float',
        'periods' => '\OpenAPI\Client\Model\FinancialPeriodAmountDto[]',
        'last_modified_date_time' => '\DateTime',
        'branch_number' => '\OpenAPI\Client\Model\BranchNumberInBudgetDto',
        'time_stamp' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'financial_year' => null,
        'released' => null,
        'released_amount' => 'double',
        'account' => null,
        'subaccount' => null,
        'description' => null,
        'amount' => 'double',
        'distributed_amount' => 'double',
        'periods' => null,
        'last_modified_date_time' => 'date-time',
        'branch_number' => null,
        'time_stamp' => 'byte'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'financial_year' => false,
        'released' => false,
        'released_amount' => false,
        'account' => false,
        'subaccount' => false,
        'description' => false,
        'amount' => false,
        'distributed_amount' => false,
        'periods' => false,
        'last_modified_date_time' => false,
        'branch_number' => false,
        'time_stamp' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'financial_year' => 'financialYear',
        'released' => 'released',
        'released_amount' => 'releasedAmount',
        'account' => 'account',
        'subaccount' => 'subaccount',
        'description' => 'description',
        'amount' => 'amount',
        'distributed_amount' => 'distributedAmount',
        'periods' => 'periods',
        'last_modified_date_time' => 'lastModifiedDateTime',
        'branch_number' => 'branchNumber',
        'time_stamp' => 'timeStamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'financial_year' => 'setFinancialYear',
        'released' => 'setReleased',
        'released_amount' => 'setReleasedAmount',
        'account' => 'setAccount',
        'subaccount' => 'setSubaccount',
        'description' => 'setDescription',
        'amount' => 'setAmount',
        'distributed_amount' => 'setDistributedAmount',
        'periods' => 'setPeriods',
        'last_modified_date_time' => 'setLastModifiedDateTime',
        'branch_number' => 'setBranchNumber',
        'time_stamp' => 'setTimeStamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'financial_year' => 'getFinancialYear',
        'released' => 'getReleased',
        'released_amount' => 'getReleasedAmount',
        'account' => 'getAccount',
        'subaccount' => 'getSubaccount',
        'description' => 'getDescription',
        'amount' => 'getAmount',
        'distributed_amount' => 'getDistributedAmount',
        'periods' => 'getPeriods',
        'last_modified_date_time' => 'getLastModifiedDateTime',
        'branch_number' => 'getBranchNumber',
        'time_stamp' => 'getTimeStamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('financial_year', $data ?? [], null);
        $this->setIfExists('released', $data ?? [], null);
        $this->setIfExists('released_amount', $data ?? [], null);
        $this->setIfExists('account', $data ?? [], null);
        $this->setIfExists('subaccount', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('distributed_amount', $data ?? [], null);
        $this->setIfExists('periods', $data ?? [], null);
        $this->setIfExists('last_modified_date_time', $data ?? [], null);
        $this->setIfExists('branch_number', $data ?? [], null);
        $this->setIfExists('time_stamp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets financial_year
     *
     * @return string|null
     */
    public function getFinancialYear()
    {
        return $this->container['financial_year'];
    }

    /**
     * Sets financial_year
     *
     * @param string|null $financial_year Mandatory field: The top part &gt; Financial year* &gt; The financial year of the budget.
     *
     * @return self
     */
    public function setFinancialYear($financial_year)
    {
        if (is_null($financial_year)) {
            throw new \InvalidArgumentException('non-nullable financial_year cannot be null');
        }
        $this->container['financial_year'] = $financial_year;

        return $this;
    }

    /**
     * Gets released
     *
     * @return bool|null
     */
    public function getReleased()
    {
        return $this->container['released'];
    }

    /**
     * Sets released
     *
     * @param bool|null $released The budget area &gt; The budget articles pane &gt; Released &gt; A check box that indicates (if selected) that the budget article has been released.
     *
     * @return self
     */
    public function setReleased($released)
    {
        if (is_null($released)) {
            throw new \InvalidArgumentException('non-nullable released cannot be null');
        }
        $this->container['released'] = $released;

        return $this;
    }

    /**
     * Gets released_amount
     *
     * @return float|null
     */
    public function getReleasedAmount()
    {
        return $this->container['released_amount'];
    }

    /**
     * Sets released_amount
     *
     * @param float|null $released_amount The budget area &gt; The budget articles pane &gt; Released amount &gt; The amount that has been released for this article.
     *
     * @return self
     */
    public function setReleasedAmount($released_amount)
    {
        if (is_null($released_amount)) {
            throw new \InvalidArgumentException('non-nullable released_amount cannot be null');
        }
        $this->container['released_amount'] = $released_amount;

        return $this;
    }

    /**
     * Gets account
     *
     * @return \OpenAPI\Client\Model\AccountInBudgetDto|null
     */
    public function getAccount()
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param \OpenAPI\Client\Model\AccountInBudgetDto|null $account account
     *
     * @return self
     */
    public function setAccount($account)
    {
        if (is_null($account)) {
            throw new \InvalidArgumentException('non-nullable account cannot be null');
        }
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets subaccount
     *
     * @return \OpenAPI\Client\Model\SubaccountInBudgetDto|null
     */
    public function getSubaccount()
    {
        return $this->container['subaccount'];
    }

    /**
     * Sets subaccount
     *
     * @param \OpenAPI\Client\Model\SubaccountInBudgetDto|null $subaccount subaccount
     *
     * @return self
     */
    public function setSubaccount($subaccount)
    {
        if (is_null($subaccount)) {
            throw new \InvalidArgumentException('non-nullable subaccount cannot be null');
        }
        $this->container['subaccount'] = $subaccount;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Mandatory field: The budget area &gt; The budget articles pane &gt; Description* &gt; A description of the budget article.By default, this column displays the account description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount The budget area &gt; The budget articles pane &gt; Amount &gt; The article amount.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets distributed_amount
     *
     * @return float|null
     */
    public function getDistributedAmount()
    {
        return $this->container['distributed_amount'];
    }

    /**
     * Sets distributed_amount
     *
     * @param float|null $distributed_amount The budget area  The budget articles pane &gt; Distributed amount &gt; The amount distributed over the periods.
     *
     * @return self
     */
    public function setDistributedAmount($distributed_amount)
    {
        if (is_null($distributed_amount)) {
            throw new \InvalidArgumentException('non-nullable distributed_amount cannot be null');
        }
        $this->container['distributed_amount'] = $distributed_amount;

        return $this;
    }

    /**
     * Gets periods
     *
     * @return \OpenAPI\Client\Model\FinancialPeriodAmountDto[]|null
     */
    public function getPeriods()
    {
        return $this->container['periods'];
    }

    /**
     * Sets periods
     *
     * @param \OpenAPI\Client\Model\FinancialPeriodAmountDto[]|null $periods The budget area The budget articles pane &gt; Period XX &gt; Amount per period within the financial year.
     *
     * @return self
     */
    public function setPeriods($periods)
    {
        if (is_null($periods)) {
            throw new \InvalidArgumentException('non-nullable periods cannot be null');
        }
        $this->container['periods'] = $periods;

        return $this;
    }

    /**
     * Gets last_modified_date_time
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDateTime()
    {
        return $this->container['last_modified_date_time'];
    }

    /**
     * Sets last_modified_date_time
     *
     * @param \DateTime|null $last_modified_date_time A system generated date/time not visible in the window.
     *
     * @return self
     */
    public function setLastModifiedDateTime($last_modified_date_time)
    {
        if (is_null($last_modified_date_time)) {
            throw new \InvalidArgumentException('non-nullable last_modified_date_time cannot be null');
        }
        $this->container['last_modified_date_time'] = $last_modified_date_time;

        return $this;
    }

    /**
     * Gets branch_number
     *
     * @return \OpenAPI\Client\Model\BranchNumberInBudgetDto|null
     */
    public function getBranchNumber()
    {
        return $this->container['branch_number'];
    }

    /**
     * Sets branch_number
     *
     * @param \OpenAPI\Client\Model\BranchNumberInBudgetDto|null $branch_number branch_number
     *
     * @return self
     */
    public function setBranchNumber($branch_number)
    {
        if (is_null($branch_number)) {
            throw new \InvalidArgumentException('non-nullable branch_number cannot be null');
        }
        $this->container['branch_number'] = $branch_number;

        return $this;
    }

    /**
     * Gets time_stamp
     *
     * @return string|null
     */
    public function getTimeStamp()
    {
        return $this->container['time_stamp'];
    }

    /**
     * Sets time_stamp
     *
     * @param string|null $time_stamp The timestamp of the budget article, used for concurrency control.
     *
     * @return self
     */
    public function setTimeStamp($time_stamp)
    {
        if (is_null($time_stamp)) {
            throw new \InvalidArgumentException('non-nullable time_stamp cannot be null');
        }
        $this->container['time_stamp'] = $time_stamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


