<?php
/**
 * DiscountUpdateDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DiscountUpdateDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DiscountUpdateDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DiscountUpdateDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'discount_code' => '\OpenAPI\Client\Model\DtoValueOfString',
        'series' => '\OpenAPI\Client\Model\DtoValueOfString',
        'description' => '\OpenAPI\Client\Model\DtoValueOfString',
        'discount_by' => '\OpenAPI\Client\Model\DtoValueOfString',
        'break_by' => '\OpenAPI\Client\Model\DtoValueOfString',
        'promotional' => '\OpenAPI\Client\Model\DtoValueOfBoolean',
        'active' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'prorate_discount' => '\OpenAPI\Client\Model\DtoValueOfBoolean',
        'effective_date' => '\OpenAPI\Client\Model\DtoValueOfNullableOfDateTime',
        'expiration_date' => '\OpenAPI\Client\Model\DtoValueOfNullableOfDateTime',
        'discount_breakpoints' => '\OpenAPI\Client\Model\DiscountBreakpointUpdateDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'discount_code' => null,
        'series' => null,
        'description' => null,
        'discount_by' => null,
        'break_by' => null,
        'promotional' => null,
        'active' => null,
        'prorate_discount' => null,
        'effective_date' => null,
        'expiration_date' => null,
        'discount_breakpoints' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'discount_code' => false,
        'series' => false,
        'description' => false,
        'discount_by' => false,
        'break_by' => false,
        'promotional' => false,
        'active' => false,
        'prorate_discount' => false,
        'effective_date' => false,
        'expiration_date' => false,
        'discount_breakpoints' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'discount_code' => 'discountCode',
        'series' => 'series',
        'description' => 'description',
        'discount_by' => 'discountBy',
        'break_by' => 'breakBy',
        'promotional' => 'promotional',
        'active' => 'active',
        'prorate_discount' => 'prorateDiscount',
        'effective_date' => 'effectiveDate',
        'expiration_date' => 'expirationDate',
        'discount_breakpoints' => 'discountBreakpoints'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'discount_code' => 'setDiscountCode',
        'series' => 'setSeries',
        'description' => 'setDescription',
        'discount_by' => 'setDiscountBy',
        'break_by' => 'setBreakBy',
        'promotional' => 'setPromotional',
        'active' => 'setActive',
        'prorate_discount' => 'setProrateDiscount',
        'effective_date' => 'setEffectiveDate',
        'expiration_date' => 'setExpirationDate',
        'discount_breakpoints' => 'setDiscountBreakpoints'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'discount_code' => 'getDiscountCode',
        'series' => 'getSeries',
        'description' => 'getDescription',
        'discount_by' => 'getDiscountBy',
        'break_by' => 'getBreakBy',
        'promotional' => 'getPromotional',
        'active' => 'getActive',
        'prorate_discount' => 'getProrateDiscount',
        'effective_date' => 'getEffectiveDate',
        'expiration_date' => 'getExpirationDate',
        'discount_breakpoints' => 'getDiscountBreakpoints'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('discount_code', $data ?? [], null);
        $this->setIfExists('series', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('discount_by', $data ?? [], null);
        $this->setIfExists('break_by', $data ?? [], null);
        $this->setIfExists('promotional', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('prorate_discount', $data ?? [], null);
        $this->setIfExists('effective_date', $data ?? [], null);
        $this->setIfExists('expiration_date', $data ?? [], null);
        $this->setIfExists('discount_breakpoints', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets discount_code
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getDiscountCode()
    {
        return $this->container['discount_code'];
    }

    /**
     * Sets discount_code
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $discount_code discount_code
     *
     * @return self
     */
    public function setDiscountCode($discount_code)
    {
        if (is_null($discount_code)) {
            throw new \InvalidArgumentException('non-nullable discount_code cannot be null');
        }
        $this->container['discount_code'] = $discount_code;

        return $this;
    }

    /**
     * Gets series
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getSeries()
    {
        return $this->container['series'];
    }

    /**
     * Sets series
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $series series
     *
     * @return self
     */
    public function setSeries($series)
    {
        if (is_null($series)) {
            throw new \InvalidArgumentException('non-nullable series cannot be null');
        }
        $this->container['series'] = $series;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets discount_by
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getDiscountBy()
    {
        return $this->container['discount_by'];
    }

    /**
     * Sets discount_by
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $discount_by discount_by
     *
     * @return self
     */
    public function setDiscountBy($discount_by)
    {
        if (is_null($discount_by)) {
            throw new \InvalidArgumentException('non-nullable discount_by cannot be null');
        }
        $this->container['discount_by'] = $discount_by;

        return $this;
    }

    /**
     * Gets break_by
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getBreakBy()
    {
        return $this->container['break_by'];
    }

    /**
     * Sets break_by
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $break_by break_by
     *
     * @return self
     */
    public function setBreakBy($break_by)
    {
        if (is_null($break_by)) {
            throw new \InvalidArgumentException('non-nullable break_by cannot be null');
        }
        $this->container['break_by'] = $break_by;

        return $this;
    }

    /**
     * Gets promotional
     *
     * @return \OpenAPI\Client\Model\DtoValueOfBoolean|null
     */
    public function getPromotional()
    {
        return $this->container['promotional'];
    }

    /**
     * Sets promotional
     *
     * @param \OpenAPI\Client\Model\DtoValueOfBoolean|null $promotional promotional
     *
     * @return self
     */
    public function setPromotional($promotional)
    {
        if (is_null($promotional)) {
            throw new \InvalidArgumentException('non-nullable promotional cannot be null');
        }
        $this->container['promotional'] = $promotional;

        return $this;
    }

    /**
     * Gets active
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $active active
     *
     * @return self
     */
    public function setActive($active)
    {
        if (is_null($active)) {
            throw new \InvalidArgumentException('non-nullable active cannot be null');
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets prorate_discount
     *
     * @return \OpenAPI\Client\Model\DtoValueOfBoolean|null
     */
    public function getProrateDiscount()
    {
        return $this->container['prorate_discount'];
    }

    /**
     * Sets prorate_discount
     *
     * @param \OpenAPI\Client\Model\DtoValueOfBoolean|null $prorate_discount prorate_discount
     *
     * @return self
     */
    public function setProrateDiscount($prorate_discount)
    {
        if (is_null($prorate_discount)) {
            throw new \InvalidArgumentException('non-nullable prorate_discount cannot be null');
        }
        $this->container['prorate_discount'] = $prorate_discount;

        return $this;
    }

    /**
     * Gets effective_date
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfDateTime|null
     */
    public function getEffectiveDate()
    {
        return $this->container['effective_date'];
    }

    /**
     * Sets effective_date
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfDateTime|null $effective_date effective_date
     *
     * @return self
     */
    public function setEffectiveDate($effective_date)
    {
        if (is_null($effective_date)) {
            throw new \InvalidArgumentException('non-nullable effective_date cannot be null');
        }
        $this->container['effective_date'] = $effective_date;

        return $this;
    }

    /**
     * Gets expiration_date
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfDateTime|null
     */
    public function getExpirationDate()
    {
        return $this->container['expiration_date'];
    }

    /**
     * Sets expiration_date
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfDateTime|null $expiration_date expiration_date
     *
     * @return self
     */
    public function setExpirationDate($expiration_date)
    {
        if (is_null($expiration_date)) {
            throw new \InvalidArgumentException('non-nullable expiration_date cannot be null');
        }
        $this->container['expiration_date'] = $expiration_date;

        return $this;
    }

    /**
     * Gets discount_breakpoints
     *
     * @return \OpenAPI\Client\Model\DiscountBreakpointUpdateDto[]|null
     */
    public function getDiscountBreakpoints()
    {
        return $this->container['discount_breakpoints'];
    }

    /**
     * Sets discount_breakpoints
     *
     * @param \OpenAPI\Client\Model\DiscountBreakpointUpdateDto[]|null $discount_breakpoints discount_breakpoints
     *
     * @return self
     */
    public function setDiscountBreakpoints($discount_breakpoints)
    {
        if (is_null($discount_breakpoints)) {
            throw new \InvalidArgumentException('non-nullable discount_breakpoints cannot be null');
        }
        $this->container['discount_breakpoints'] = $discount_breakpoints;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


