<?php
/**
 * ProjectUpdateDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProjectUpdateDto Class Doc Comment
 *
 * @category Class
 * @description This class represent a Project in Project Controller. Used to pass data to server for creating or updating an project
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectUpdateDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProjectUpdateDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'project_id' => '\OpenAPI\Client\Model\DtoValueOfString',
        'internal_id' => '\OpenAPI\Client\Model\DtoValueOfNullableOfInt32',
        'customer' => '\OpenAPI\Client\Model\DtoValueOfString',
        'description' => '\OpenAPI\Client\Model\DescriptionInProjectUpdateDto',
        'hold' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'template' => '\OpenAPI\Client\Model\DtoValueOfString',
        'status' => '\OpenAPI\Client\Model\DtoValueOfNullableOfProjectStatus',
        'def_account' => '\OpenAPI\Client\Model\DtoValueOfString',
        'def_sub' => '\OpenAPI\Client\Model\SegmentUpdateDto[]',
        'def_accrual_account' => '\OpenAPI\Client\Model\DtoValueOfString',
        'def_accrual_sub' => '\OpenAPI\Client\Model\SegmentUpdateDto[]',
        'start_date' => '\OpenAPI\Client\Model\StartDateInProjectUpdateDto',
        'end_date' => '\OpenAPI\Client\Model\DtoValueOfNullableOfDateTime',
        'billing_period' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBillingPeriod',
        'allocation_rule' => '\OpenAPI\Client\Model\DtoValueOfString',
        'billing_rule' => '\OpenAPI\Client\Model\DtoValueOfString',
        'branch' => '\OpenAPI\Client\Model\BranchInProjectUpdateDto',
        'rate_table' => '\OpenAPI\Client\Model\DtoValueOfString',
        'project_manger' => '\OpenAPI\Client\Model\DtoValueOfString',
        'project_manager_internal_id' => '\OpenAPI\Client\Model\DtoValueOfNullableOfInt32',
        'auto_allocate' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'automatic_release_ar_doc' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'restric_employees' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'restric_equipment' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'customer_location' => '\OpenAPI\Client\Model\DtoValueOfString',
        'visibility' => '\OpenAPI\Client\Model\VisibilityUpdateDto',
        'tasks' => '\OpenAPI\Client\Model\TaskUpdateDto[]',
        'employees' => '\OpenAPI\Client\Model\ProjectEmployeeUpdateDto[]',
        'note' => '\OpenAPI\Client\Model\DtoValueOfString'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'project_id' => null,
        'internal_id' => null,
        'customer' => null,
        'description' => null,
        'hold' => null,
        'template' => null,
        'status' => null,
        'def_account' => null,
        'def_sub' => null,
        'def_accrual_account' => null,
        'def_accrual_sub' => null,
        'start_date' => null,
        'end_date' => null,
        'billing_period' => null,
        'allocation_rule' => null,
        'billing_rule' => null,
        'branch' => null,
        'rate_table' => null,
        'project_manger' => null,
        'project_manager_internal_id' => null,
        'auto_allocate' => null,
        'automatic_release_ar_doc' => null,
        'restric_employees' => null,
        'restric_equipment' => null,
        'customer_location' => null,
        'visibility' => null,
        'tasks' => null,
        'employees' => null,
        'note' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'project_id' => false,
        'internal_id' => false,
        'customer' => false,
        'description' => false,
        'hold' => false,
        'template' => false,
        'status' => false,
        'def_account' => false,
        'def_sub' => false,
        'def_accrual_account' => false,
        'def_accrual_sub' => false,
        'start_date' => false,
        'end_date' => false,
        'billing_period' => false,
        'allocation_rule' => false,
        'billing_rule' => false,
        'branch' => false,
        'rate_table' => false,
        'project_manger' => false,
        'project_manager_internal_id' => false,
        'auto_allocate' => false,
        'automatic_release_ar_doc' => false,
        'restric_employees' => false,
        'restric_equipment' => false,
        'customer_location' => false,
        'visibility' => false,
        'tasks' => false,
        'employees' => false,
        'note' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'project_id' => 'projectID',
        'internal_id' => 'internalID',
        'customer' => 'customer',
        'description' => 'description',
        'hold' => 'hold',
        'template' => 'template',
        'status' => 'status',
        'def_account' => 'defAccount',
        'def_sub' => 'defSub',
        'def_accrual_account' => 'defAccrualAccount',
        'def_accrual_sub' => 'defAccrualSub',
        'start_date' => 'startDate',
        'end_date' => 'endDate',
        'billing_period' => 'billingPeriod',
        'allocation_rule' => 'allocationRule',
        'billing_rule' => 'billingRule',
        'branch' => 'branch',
        'rate_table' => 'rateTable',
        'project_manger' => 'projectManger',
        'project_manager_internal_id' => 'projectManagerInternalId',
        'auto_allocate' => 'autoAllocate',
        'automatic_release_ar_doc' => 'automaticReleaseArDoc',
        'restric_employees' => 'restricEmployees',
        'restric_equipment' => 'restricEquipment',
        'customer_location' => 'customerLocation',
        'visibility' => 'visibility',
        'tasks' => 'tasks',
        'employees' => 'employees',
        'note' => 'note'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'project_id' => 'setProjectId',
        'internal_id' => 'setInternalId',
        'customer' => 'setCustomer',
        'description' => 'setDescription',
        'hold' => 'setHold',
        'template' => 'setTemplate',
        'status' => 'setStatus',
        'def_account' => 'setDefAccount',
        'def_sub' => 'setDefSub',
        'def_accrual_account' => 'setDefAccrualAccount',
        'def_accrual_sub' => 'setDefAccrualSub',
        'start_date' => 'setStartDate',
        'end_date' => 'setEndDate',
        'billing_period' => 'setBillingPeriod',
        'allocation_rule' => 'setAllocationRule',
        'billing_rule' => 'setBillingRule',
        'branch' => 'setBranch',
        'rate_table' => 'setRateTable',
        'project_manger' => 'setProjectManger',
        'project_manager_internal_id' => 'setProjectManagerInternalId',
        'auto_allocate' => 'setAutoAllocate',
        'automatic_release_ar_doc' => 'setAutomaticReleaseArDoc',
        'restric_employees' => 'setRestricEmployees',
        'restric_equipment' => 'setRestricEquipment',
        'customer_location' => 'setCustomerLocation',
        'visibility' => 'setVisibility',
        'tasks' => 'setTasks',
        'employees' => 'setEmployees',
        'note' => 'setNote'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'project_id' => 'getProjectId',
        'internal_id' => 'getInternalId',
        'customer' => 'getCustomer',
        'description' => 'getDescription',
        'hold' => 'getHold',
        'template' => 'getTemplate',
        'status' => 'getStatus',
        'def_account' => 'getDefAccount',
        'def_sub' => 'getDefSub',
        'def_accrual_account' => 'getDefAccrualAccount',
        'def_accrual_sub' => 'getDefAccrualSub',
        'start_date' => 'getStartDate',
        'end_date' => 'getEndDate',
        'billing_period' => 'getBillingPeriod',
        'allocation_rule' => 'getAllocationRule',
        'billing_rule' => 'getBillingRule',
        'branch' => 'getBranch',
        'rate_table' => 'getRateTable',
        'project_manger' => 'getProjectManger',
        'project_manager_internal_id' => 'getProjectManagerInternalId',
        'auto_allocate' => 'getAutoAllocate',
        'automatic_release_ar_doc' => 'getAutomaticReleaseArDoc',
        'restric_employees' => 'getRestricEmployees',
        'restric_equipment' => 'getRestricEquipment',
        'customer_location' => 'getCustomerLocation',
        'visibility' => 'getVisibility',
        'tasks' => 'getTasks',
        'employees' => 'getEmployees',
        'note' => 'getNote'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('internal_id', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('hold', $data ?? [], null);
        $this->setIfExists('template', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('def_account', $data ?? [], null);
        $this->setIfExists('def_sub', $data ?? [], null);
        $this->setIfExists('def_accrual_account', $data ?? [], null);
        $this->setIfExists('def_accrual_sub', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('billing_period', $data ?? [], null);
        $this->setIfExists('allocation_rule', $data ?? [], null);
        $this->setIfExists('billing_rule', $data ?? [], null);
        $this->setIfExists('branch', $data ?? [], null);
        $this->setIfExists('rate_table', $data ?? [], null);
        $this->setIfExists('project_manger', $data ?? [], null);
        $this->setIfExists('project_manager_internal_id', $data ?? [], null);
        $this->setIfExists('auto_allocate', $data ?? [], null);
        $this->setIfExists('automatic_release_ar_doc', $data ?? [], null);
        $this->setIfExists('restric_employees', $data ?? [], null);
        $this->setIfExists('restric_equipment', $data ?? [], null);
        $this->setIfExists('customer_location', $data ?? [], null);
        $this->setIfExists('visibility', $data ?? [], null);
        $this->setIfExists('tasks', $data ?? [], null);
        $this->setIfExists('employees', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['start_date'] === null) {
            $invalidProperties[] = "'start_date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets project_id
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets internal_id
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfInt32|null
     */
    public function getInternalId()
    {
        return $this->container['internal_id'];
    }

    /**
     * Sets internal_id
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfInt32|null $internal_id internal_id
     *
     * @return self
     */
    public function setInternalId($internal_id)
    {
        if (is_null($internal_id)) {
            throw new \InvalidArgumentException('non-nullable internal_id cannot be null');
        }
        $this->container['internal_id'] = $internal_id;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \OpenAPI\Client\Model\DescriptionInProjectUpdateDto
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \OpenAPI\Client\Model\DescriptionInProjectUpdateDto $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets hold
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getHold()
    {
        return $this->container['hold'];
    }

    /**
     * Sets hold
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $hold hold
     *
     * @return self
     */
    public function setHold($hold)
    {
        if (is_null($hold)) {
            throw new \InvalidArgumentException('non-nullable hold cannot be null');
        }
        $this->container['hold'] = $hold;

        return $this;
    }

    /**
     * Gets template
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $template template
     *
     * @return self
     */
    public function setTemplate($template)
    {
        if (is_null($template)) {
            throw new \InvalidArgumentException('non-nullable template cannot be null');
        }
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfProjectStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfProjectStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets def_account
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getDefAccount()
    {
        return $this->container['def_account'];
    }

    /**
     * Sets def_account
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $def_account def_account
     *
     * @return self
     */
    public function setDefAccount($def_account)
    {
        if (is_null($def_account)) {
            throw new \InvalidArgumentException('non-nullable def_account cannot be null');
        }
        $this->container['def_account'] = $def_account;

        return $this;
    }

    /**
     * Gets def_sub
     *
     * @return \OpenAPI\Client\Model\SegmentUpdateDto[]|null
     */
    public function getDefSub()
    {
        return $this->container['def_sub'];
    }

    /**
     * Sets def_sub
     *
     * @param \OpenAPI\Client\Model\SegmentUpdateDto[]|null $def_sub Mandatory field when Project Template is not specified.
     *
     * @return self
     */
    public function setDefSub($def_sub)
    {
        if (is_null($def_sub)) {
            throw new \InvalidArgumentException('non-nullable def_sub cannot be null');
        }
        $this->container['def_sub'] = $def_sub;

        return $this;
    }

    /**
     * Gets def_accrual_account
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getDefAccrualAccount()
    {
        return $this->container['def_accrual_account'];
    }

    /**
     * Sets def_accrual_account
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $def_accrual_account def_accrual_account
     *
     * @return self
     */
    public function setDefAccrualAccount($def_accrual_account)
    {
        if (is_null($def_accrual_account)) {
            throw new \InvalidArgumentException('non-nullable def_accrual_account cannot be null');
        }
        $this->container['def_accrual_account'] = $def_accrual_account;

        return $this;
    }

    /**
     * Gets def_accrual_sub
     *
     * @return \OpenAPI\Client\Model\SegmentUpdateDto[]|null
     */
    public function getDefAccrualSub()
    {
        return $this->container['def_accrual_sub'];
    }

    /**
     * Sets def_accrual_sub
     *
     * @param \OpenAPI\Client\Model\SegmentUpdateDto[]|null $def_accrual_sub def_accrual_sub
     *
     * @return self
     */
    public function setDefAccrualSub($def_accrual_sub)
    {
        if (is_null($def_accrual_sub)) {
            throw new \InvalidArgumentException('non-nullable def_accrual_sub cannot be null');
        }
        $this->container['def_accrual_sub'] = $def_accrual_sub;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return \OpenAPI\Client\Model\StartDateInProjectUpdateDto
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \OpenAPI\Client\Model\StartDateInProjectUpdateDto $start_date start_date
     *
     * @return self
     */
    public function setStartDate($start_date)
    {
        if (is_null($start_date)) {
            throw new \InvalidArgumentException('non-nullable start_date cannot be null');
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfDateTime|null
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfDateTime|null $end_date end_date
     *
     * @return self
     */
    public function setEndDate($end_date)
    {
        if (is_null($end_date)) {
            throw new \InvalidArgumentException('non-nullable end_date cannot be null');
        }
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets billing_period
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBillingPeriod|null
     */
    public function getBillingPeriod()
    {
        return $this->container['billing_period'];
    }

    /**
     * Sets billing_period
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBillingPeriod|null $billing_period billing_period
     *
     * @return self
     */
    public function setBillingPeriod($billing_period)
    {
        if (is_null($billing_period)) {
            throw new \InvalidArgumentException('non-nullable billing_period cannot be null');
        }
        $this->container['billing_period'] = $billing_period;

        return $this;
    }

    /**
     * Gets allocation_rule
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getAllocationRule()
    {
        return $this->container['allocation_rule'];
    }

    /**
     * Sets allocation_rule
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $allocation_rule allocation_rule
     *
     * @return self
     */
    public function setAllocationRule($allocation_rule)
    {
        if (is_null($allocation_rule)) {
            throw new \InvalidArgumentException('non-nullable allocation_rule cannot be null');
        }
        $this->container['allocation_rule'] = $allocation_rule;

        return $this;
    }

    /**
     * Gets billing_rule
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getBillingRule()
    {
        return $this->container['billing_rule'];
    }

    /**
     * Sets billing_rule
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $billing_rule billing_rule
     *
     * @return self
     */
    public function setBillingRule($billing_rule)
    {
        if (is_null($billing_rule)) {
            throw new \InvalidArgumentException('non-nullable billing_rule cannot be null');
        }
        $this->container['billing_rule'] = $billing_rule;

        return $this;
    }

    /**
     * Gets branch
     *
     * @return \OpenAPI\Client\Model\BranchInProjectUpdateDto|null
     */
    public function getBranch()
    {
        return $this->container['branch'];
    }

    /**
     * Sets branch
     *
     * @param \OpenAPI\Client\Model\BranchInProjectUpdateDto|null $branch branch
     *
     * @return self
     */
    public function setBranch($branch)
    {
        if (is_null($branch)) {
            throw new \InvalidArgumentException('non-nullable branch cannot be null');
        }
        $this->container['branch'] = $branch;

        return $this;
    }

    /**
     * Gets rate_table
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getRateTable()
    {
        return $this->container['rate_table'];
    }

    /**
     * Sets rate_table
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $rate_table rate_table
     *
     * @return self
     */
    public function setRateTable($rate_table)
    {
        if (is_null($rate_table)) {
            throw new \InvalidArgumentException('non-nullable rate_table cannot be null');
        }
        $this->container['rate_table'] = $rate_table;

        return $this;
    }

    /**
     * Gets project_manger
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getProjectManger()
    {
        return $this->container['project_manger'];
    }

    /**
     * Sets project_manger
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $project_manger project_manger
     *
     * @return self
     */
    public function setProjectManger($project_manger)
    {
        if (is_null($project_manger)) {
            throw new \InvalidArgumentException('non-nullable project_manger cannot be null');
        }
        $this->container['project_manger'] = $project_manger;

        return $this;
    }

    /**
     * Gets project_manager_internal_id
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfInt32|null
     */
    public function getProjectManagerInternalId()
    {
        return $this->container['project_manager_internal_id'];
    }

    /**
     * Sets project_manager_internal_id
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfInt32|null $project_manager_internal_id project_manager_internal_id
     *
     * @return self
     */
    public function setProjectManagerInternalId($project_manager_internal_id)
    {
        if (is_null($project_manager_internal_id)) {
            throw new \InvalidArgumentException('non-nullable project_manager_internal_id cannot be null');
        }
        $this->container['project_manager_internal_id'] = $project_manager_internal_id;

        return $this;
    }

    /**
     * Gets auto_allocate
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getAutoAllocate()
    {
        return $this->container['auto_allocate'];
    }

    /**
     * Sets auto_allocate
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $auto_allocate auto_allocate
     *
     * @return self
     */
    public function setAutoAllocate($auto_allocate)
    {
        if (is_null($auto_allocate)) {
            throw new \InvalidArgumentException('non-nullable auto_allocate cannot be null');
        }
        $this->container['auto_allocate'] = $auto_allocate;

        return $this;
    }

    /**
     * Gets automatic_release_ar_doc
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getAutomaticReleaseArDoc()
    {
        return $this->container['automatic_release_ar_doc'];
    }

    /**
     * Sets automatic_release_ar_doc
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $automatic_release_ar_doc automatic_release_ar_doc
     *
     * @return self
     */
    public function setAutomaticReleaseArDoc($automatic_release_ar_doc)
    {
        if (is_null($automatic_release_ar_doc)) {
            throw new \InvalidArgumentException('non-nullable automatic_release_ar_doc cannot be null');
        }
        $this->container['automatic_release_ar_doc'] = $automatic_release_ar_doc;

        return $this;
    }

    /**
     * Gets restric_employees
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getRestricEmployees()
    {
        return $this->container['restric_employees'];
    }

    /**
     * Sets restric_employees
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $restric_employees restric_employees
     *
     * @return self
     */
    public function setRestricEmployees($restric_employees)
    {
        if (is_null($restric_employees)) {
            throw new \InvalidArgumentException('non-nullable restric_employees cannot be null');
        }
        $this->container['restric_employees'] = $restric_employees;

        return $this;
    }

    /**
     * Gets restric_equipment
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getRestricEquipment()
    {
        return $this->container['restric_equipment'];
    }

    /**
     * Sets restric_equipment
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $restric_equipment restric_equipment
     *
     * @return self
     */
    public function setRestricEquipment($restric_equipment)
    {
        if (is_null($restric_equipment)) {
            throw new \InvalidArgumentException('non-nullable restric_equipment cannot be null');
        }
        $this->container['restric_equipment'] = $restric_equipment;

        return $this;
    }

    /**
     * Gets customer_location
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getCustomerLocation()
    {
        return $this->container['customer_location'];
    }

    /**
     * Sets customer_location
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $customer_location customer_location
     *
     * @return self
     */
    public function setCustomerLocation($customer_location)
    {
        if (is_null($customer_location)) {
            throw new \InvalidArgumentException('non-nullable customer_location cannot be null');
        }
        $this->container['customer_location'] = $customer_location;

        return $this;
    }

    /**
     * Gets visibility
     *
     * @return \OpenAPI\Client\Model\VisibilityUpdateDto|null
     */
    public function getVisibility()
    {
        return $this->container['visibility'];
    }

    /**
     * Sets visibility
     *
     * @param \OpenAPI\Client\Model\VisibilityUpdateDto|null $visibility visibility
     *
     * @return self
     */
    public function setVisibility($visibility)
    {
        if (is_null($visibility)) {
            throw new \InvalidArgumentException('non-nullable visibility cannot be null');
        }
        $this->container['visibility'] = $visibility;

        return $this;
    }

    /**
     * Gets tasks
     *
     * @return \OpenAPI\Client\Model\TaskUpdateDto[]|null
     */
    public function getTasks()
    {
        return $this->container['tasks'];
    }

    /**
     * Sets tasks
     *
     * @param \OpenAPI\Client\Model\TaskUpdateDto[]|null $tasks tasks
     *
     * @return self
     */
    public function setTasks($tasks)
    {
        if (is_null($tasks)) {
            throw new \InvalidArgumentException('non-nullable tasks cannot be null');
        }
        $this->container['tasks'] = $tasks;

        return $this;
    }

    /**
     * Gets employees
     *
     * @return \OpenAPI\Client\Model\ProjectEmployeeUpdateDto[]|null
     */
    public function getEmployees()
    {
        return $this->container['employees'];
    }

    /**
     * Sets employees
     *
     * @param \OpenAPI\Client\Model\ProjectEmployeeUpdateDto[]|null $employees employees
     *
     * @return self
     */
    public function setEmployees($employees)
    {
        if (is_null($employees)) {
            throw new \InvalidArgumentException('non-nullable employees cannot be null');
        }
        $this->container['employees'] = $employees;

        return $this;
    }

    /**
     * Gets note
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            throw new \InvalidArgumentException('non-nullable note cannot be null');
        }
        $this->container['note'] = $note;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


