<?php
/**
 * SalesPersonUpdateDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SalesPersonUpdateDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SalesPersonUpdateDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SalesPersonUpdateDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'salesperson_id' => '\OpenAPI\Client\Model\DtoValueOfString',
        'name' => '\OpenAPI\Client\Model\DtoValueOfString',
        'is_active' => '\OpenAPI\Client\Model\DtoValueOfNullableOfBoolean',
        'commission_pct' => '\OpenAPI\Client\Model\DtoValueOfNullableOfDecimal',
        'sales_sub' => '\OpenAPI\Client\Model\DtoValueOfString',
        'customers' => '\OpenAPI\Client\Model\CustSalesPeopleUpdateDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'salesperson_id' => null,
        'name' => null,
        'is_active' => null,
        'commission_pct' => null,
        'sales_sub' => null,
        'customers' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'salesperson_id' => false,
        'name' => false,
        'is_active' => false,
        'commission_pct' => false,
        'sales_sub' => false,
        'customers' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'salesperson_id' => 'salespersonID',
        'name' => 'name',
        'is_active' => 'isActive',
        'commission_pct' => 'commissionPct',
        'sales_sub' => 'salesSub',
        'customers' => 'customers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'salesperson_id' => 'setSalespersonId',
        'name' => 'setName',
        'is_active' => 'setIsActive',
        'commission_pct' => 'setCommissionPct',
        'sales_sub' => 'setSalesSub',
        'customers' => 'setCustomers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'salesperson_id' => 'getSalespersonId',
        'name' => 'getName',
        'is_active' => 'getIsActive',
        'commission_pct' => 'getCommissionPct',
        'sales_sub' => 'getSalesSub',
        'customers' => 'getCustomers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('salesperson_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('commission_pct', $data ?? [], null);
        $this->setIfExists('sales_sub', $data ?? [], null);
        $this->setIfExists('customers', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets salesperson_id
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getSalespersonId()
    {
        return $this->container['salesperson_id'];
    }

    /**
     * Sets salesperson_id
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $salesperson_id salesperson_id
     *
     * @return self
     */
    public function setSalespersonId($salesperson_id)
    {
        if (is_null($salesperson_id)) {
            throw new \InvalidArgumentException('non-nullable salesperson_id cannot be null');
        }
        $this->container['salesperson_id'] = $salesperson_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfBoolean|null $is_active is_active
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets commission_pct
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfDecimal|null
     */
    public function getCommissionPct()
    {
        return $this->container['commission_pct'];
    }

    /**
     * Sets commission_pct
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfDecimal|null $commission_pct commission_pct
     *
     * @return self
     */
    public function setCommissionPct($commission_pct)
    {
        if (is_null($commission_pct)) {
            throw new \InvalidArgumentException('non-nullable commission_pct cannot be null');
        }
        $this->container['commission_pct'] = $commission_pct;

        return $this;
    }

    /**
     * Gets sales_sub
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getSalesSub()
    {
        return $this->container['sales_sub'];
    }

    /**
     * Sets sales_sub
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $sales_sub sales_sub
     *
     * @return self
     */
    public function setSalesSub($sales_sub)
    {
        if (is_null($sales_sub)) {
            throw new \InvalidArgumentException('non-nullable sales_sub cannot be null');
        }
        $this->container['sales_sub'] = $sales_sub;

        return $this;
    }

    /**
     * Gets customers
     *
     * @return \OpenAPI\Client\Model\CustSalesPeopleUpdateDto[]|null
     */
    public function getCustomers()
    {
        return $this->container['customers'];
    }

    /**
     * Sets customers
     *
     * @param \OpenAPI\Client\Model\CustSalesPeopleUpdateDto[]|null $customers customers
     *
     * @return self
     */
    public function setCustomers($customers)
    {
        if (is_null($customers)) {
            throw new \InvalidArgumentException('non-nullable customers cannot be null');
        }
        $this->container['customers'] = $customers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


