<?php
/**
 * ShipmentDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShipmentDto Class Doc Comment
 *
 * @category Class
 * @description This class represents a Shipment in ShipmentController. Used by getting data.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'time_stamp' => 'string',
        'shipment_number' => 'string',
        'shipment_type' => 'string',
        'status' => 'string',
        'hold' => 'bool',
        'operation' => 'string',
        'shipment_date' => '\DateTime',
        'customer' => '\OpenAPI\Client\Model\CustomerInShipmentDto',
        'location' => '\OpenAPI\Client\Model\LocationInShipmentDto',
        'from_warehouse' => '\OpenAPI\Client\Model\FromWarehouseInShipmentDto',
        'to_warehouse' => '\OpenAPI\Client\Model\ToWarehouseInShipmentDto',
        'currency_id' => 'string',
        'owner' => '\OpenAPI\Client\Model\OwnerInShipmentDto',
        'shipped_quantity' => 'float',
        'shipped_weight' => 'float',
        'shipped_volume' => 'float',
        'packages' => 'int',
        'packages_weight' => 'float',
        'packages_volume' => 'float',
        'control_quantity' => 'float',
        'delivery_address' => '\OpenAPI\Client\Model\DeliveryAddressInShipmentDto',
        'delivery_contact' => '\OpenAPI\Client\Model\DeliveryContactInShipmentDto',
        'ship_via' => '\OpenAPI\Client\Model\ShipViaInShipmentDto',
        'fob_point' => '\OpenAPI\Client\Model\FobPointInShipmentDto',
        'shipping_terms' => '\OpenAPI\Client\Model\ShippingTermsInShipmentDto',
        'shipping_zone' => '\OpenAPI\Client\Model\ShippingZoneInShipmentDto',
        'residential_delivery' => 'bool',
        'saturday_delivery' => 'bool',
        'use_customer_account' => 'bool',
        'insurance' => 'bool',
        'freight_cost' => 'float',
        'freight_amt' => 'float',
        'transaction_type' => '\OpenAPI\Client\Model\TransactionTypeInShipmentDto',
        'mode_of_trasport' => '\OpenAPI\Client\Model\ModeOfTrasportInShipmentDto',
        'container' => 'bool',
        'shipment_detail_lines' => '\OpenAPI\Client\Model\ShipmentDetailLineDto[]',
        'shipment_order_lines' => '\OpenAPI\Client\Model\ShipmentOrderLineDto[]',
        'shipment_package_lines' => '\OpenAPI\Client\Model\PackageDetailLineDto[]',
        'last_modified_date_time' => '\DateTime',
        'note' => 'string',
        'custom_str1' => 'string',
        'custom_str2' => 'string',
        'custom_str3' => 'string',
        'custom_str4' => 'string',
        'custom_str5' => 'string',
        'custom_dec1' => 'float',
        'custom_dec2' => 'float',
        'custom_int1' => 'int',
        'custom_int2' => 'int',
        'custom_date_time_utc1' => '\DateTime',
        'error_info' => 'string',
        'metadata' => '\OpenAPI\Client\Model\MetadataDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'time_stamp' => 'byte',
        'shipment_number' => null,
        'shipment_type' => null,
        'status' => null,
        'hold' => null,
        'operation' => null,
        'shipment_date' => 'date-time',
        'customer' => null,
        'location' => null,
        'from_warehouse' => null,
        'to_warehouse' => null,
        'currency_id' => null,
        'owner' => null,
        'shipped_quantity' => 'double',
        'shipped_weight' => 'double',
        'shipped_volume' => 'double',
        'packages' => 'int32',
        'packages_weight' => 'double',
        'packages_volume' => 'double',
        'control_quantity' => 'double',
        'delivery_address' => null,
        'delivery_contact' => null,
        'ship_via' => null,
        'fob_point' => null,
        'shipping_terms' => null,
        'shipping_zone' => null,
        'residential_delivery' => null,
        'saturday_delivery' => null,
        'use_customer_account' => null,
        'insurance' => null,
        'freight_cost' => 'double',
        'freight_amt' => 'double',
        'transaction_type' => null,
        'mode_of_trasport' => null,
        'container' => null,
        'shipment_detail_lines' => null,
        'shipment_order_lines' => null,
        'shipment_package_lines' => null,
        'last_modified_date_time' => 'date-time',
        'note' => null,
        'custom_str1' => null,
        'custom_str2' => null,
        'custom_str3' => null,
        'custom_str4' => null,
        'custom_str5' => null,
        'custom_dec1' => 'double',
        'custom_dec2' => 'double',
        'custom_int1' => 'int32',
        'custom_int2' => 'int32',
        'custom_date_time_utc1' => 'date-time',
        'error_info' => null,
        'metadata' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'time_stamp' => false,
        'shipment_number' => false,
        'shipment_type' => false,
        'status' => false,
        'hold' => false,
        'operation' => false,
        'shipment_date' => false,
        'customer' => false,
        'location' => false,
        'from_warehouse' => false,
        'to_warehouse' => false,
        'currency_id' => false,
        'owner' => false,
        'shipped_quantity' => false,
        'shipped_weight' => false,
        'shipped_volume' => false,
        'packages' => false,
        'packages_weight' => false,
        'packages_volume' => false,
        'control_quantity' => false,
        'delivery_address' => false,
        'delivery_contact' => false,
        'ship_via' => false,
        'fob_point' => false,
        'shipping_terms' => false,
        'shipping_zone' => false,
        'residential_delivery' => false,
        'saturday_delivery' => false,
        'use_customer_account' => false,
        'insurance' => false,
        'freight_cost' => false,
        'freight_amt' => false,
        'transaction_type' => false,
        'mode_of_trasport' => false,
        'container' => false,
        'shipment_detail_lines' => false,
        'shipment_order_lines' => false,
        'shipment_package_lines' => false,
        'last_modified_date_time' => false,
        'note' => false,
        'custom_str1' => false,
        'custom_str2' => false,
        'custom_str3' => false,
        'custom_str4' => false,
        'custom_str5' => false,
        'custom_dec1' => false,
        'custom_dec2' => false,
        'custom_int1' => false,
        'custom_int2' => false,
        'custom_date_time_utc1' => false,
        'error_info' => false,
        'metadata' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'time_stamp' => 'timeStamp',
        'shipment_number' => 'shipmentNumber',
        'shipment_type' => 'shipmentType',
        'status' => 'status',
        'hold' => 'hold',
        'operation' => 'operation',
        'shipment_date' => 'shipmentDate',
        'customer' => 'customer',
        'location' => 'location',
        'from_warehouse' => 'fromWarehouse',
        'to_warehouse' => 'toWarehouse',
        'currency_id' => 'currencyId',
        'owner' => 'owner',
        'shipped_quantity' => 'shippedQuantity',
        'shipped_weight' => 'shippedWeight',
        'shipped_volume' => 'shippedVolume',
        'packages' => 'packages',
        'packages_weight' => 'packagesWeight',
        'packages_volume' => 'packagesVolume',
        'control_quantity' => 'controlQuantity',
        'delivery_address' => 'deliveryAddress',
        'delivery_contact' => 'deliveryContact',
        'ship_via' => 'shipVia',
        'fob_point' => 'fobPoint',
        'shipping_terms' => 'shippingTerms',
        'shipping_zone' => 'shippingZone',
        'residential_delivery' => 'residentialDelivery',
        'saturday_delivery' => 'saturdayDelivery',
        'use_customer_account' => 'useCustomerAccount',
        'insurance' => 'insurance',
        'freight_cost' => 'freightCost',
        'freight_amt' => 'freightAmt',
        'transaction_type' => 'transactionType',
        'mode_of_trasport' => 'modeOfTrasport',
        'container' => 'container',
        'shipment_detail_lines' => 'shipmentDetailLines',
        'shipment_order_lines' => 'shipmentOrderLines',
        'shipment_package_lines' => 'shipmentPackageLines',
        'last_modified_date_time' => 'lastModifiedDateTime',
        'note' => 'note',
        'custom_str1' => 'customStr1',
        'custom_str2' => 'customStr2',
        'custom_str3' => 'customStr3',
        'custom_str4' => 'customStr4',
        'custom_str5' => 'customStr5',
        'custom_dec1' => 'customDec1',
        'custom_dec2' => 'customDec2',
        'custom_int1' => 'customInt1',
        'custom_int2' => 'customInt2',
        'custom_date_time_utc1' => 'customDateTimeUTC1',
        'error_info' => 'errorInfo',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'time_stamp' => 'setTimeStamp',
        'shipment_number' => 'setShipmentNumber',
        'shipment_type' => 'setShipmentType',
        'status' => 'setStatus',
        'hold' => 'setHold',
        'operation' => 'setOperation',
        'shipment_date' => 'setShipmentDate',
        'customer' => 'setCustomer',
        'location' => 'setLocation',
        'from_warehouse' => 'setFromWarehouse',
        'to_warehouse' => 'setToWarehouse',
        'currency_id' => 'setCurrencyId',
        'owner' => 'setOwner',
        'shipped_quantity' => 'setShippedQuantity',
        'shipped_weight' => 'setShippedWeight',
        'shipped_volume' => 'setShippedVolume',
        'packages' => 'setPackages',
        'packages_weight' => 'setPackagesWeight',
        'packages_volume' => 'setPackagesVolume',
        'control_quantity' => 'setControlQuantity',
        'delivery_address' => 'setDeliveryAddress',
        'delivery_contact' => 'setDeliveryContact',
        'ship_via' => 'setShipVia',
        'fob_point' => 'setFobPoint',
        'shipping_terms' => 'setShippingTerms',
        'shipping_zone' => 'setShippingZone',
        'residential_delivery' => 'setResidentialDelivery',
        'saturday_delivery' => 'setSaturdayDelivery',
        'use_customer_account' => 'setUseCustomerAccount',
        'insurance' => 'setInsurance',
        'freight_cost' => 'setFreightCost',
        'freight_amt' => 'setFreightAmt',
        'transaction_type' => 'setTransactionType',
        'mode_of_trasport' => 'setModeOfTrasport',
        'container' => 'setContainer',
        'shipment_detail_lines' => 'setShipmentDetailLines',
        'shipment_order_lines' => 'setShipmentOrderLines',
        'shipment_package_lines' => 'setShipmentPackageLines',
        'last_modified_date_time' => 'setLastModifiedDateTime',
        'note' => 'setNote',
        'custom_str1' => 'setCustomStr1',
        'custom_str2' => 'setCustomStr2',
        'custom_str3' => 'setCustomStr3',
        'custom_str4' => 'setCustomStr4',
        'custom_str5' => 'setCustomStr5',
        'custom_dec1' => 'setCustomDec1',
        'custom_dec2' => 'setCustomDec2',
        'custom_int1' => 'setCustomInt1',
        'custom_int2' => 'setCustomInt2',
        'custom_date_time_utc1' => 'setCustomDateTimeUtc1',
        'error_info' => 'setErrorInfo',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'time_stamp' => 'getTimeStamp',
        'shipment_number' => 'getShipmentNumber',
        'shipment_type' => 'getShipmentType',
        'status' => 'getStatus',
        'hold' => 'getHold',
        'operation' => 'getOperation',
        'shipment_date' => 'getShipmentDate',
        'customer' => 'getCustomer',
        'location' => 'getLocation',
        'from_warehouse' => 'getFromWarehouse',
        'to_warehouse' => 'getToWarehouse',
        'currency_id' => 'getCurrencyId',
        'owner' => 'getOwner',
        'shipped_quantity' => 'getShippedQuantity',
        'shipped_weight' => 'getShippedWeight',
        'shipped_volume' => 'getShippedVolume',
        'packages' => 'getPackages',
        'packages_weight' => 'getPackagesWeight',
        'packages_volume' => 'getPackagesVolume',
        'control_quantity' => 'getControlQuantity',
        'delivery_address' => 'getDeliveryAddress',
        'delivery_contact' => 'getDeliveryContact',
        'ship_via' => 'getShipVia',
        'fob_point' => 'getFobPoint',
        'shipping_terms' => 'getShippingTerms',
        'shipping_zone' => 'getShippingZone',
        'residential_delivery' => 'getResidentialDelivery',
        'saturday_delivery' => 'getSaturdayDelivery',
        'use_customer_account' => 'getUseCustomerAccount',
        'insurance' => 'getInsurance',
        'freight_cost' => 'getFreightCost',
        'freight_amt' => 'getFreightAmt',
        'transaction_type' => 'getTransactionType',
        'mode_of_trasport' => 'getModeOfTrasport',
        'container' => 'getContainer',
        'shipment_detail_lines' => 'getShipmentDetailLines',
        'shipment_order_lines' => 'getShipmentOrderLines',
        'shipment_package_lines' => 'getShipmentPackageLines',
        'last_modified_date_time' => 'getLastModifiedDateTime',
        'note' => 'getNote',
        'custom_str1' => 'getCustomStr1',
        'custom_str2' => 'getCustomStr2',
        'custom_str3' => 'getCustomStr3',
        'custom_str4' => 'getCustomStr4',
        'custom_str5' => 'getCustomStr5',
        'custom_dec1' => 'getCustomDec1',
        'custom_dec2' => 'getCustomDec2',
        'custom_int1' => 'getCustomInt1',
        'custom_int2' => 'getCustomInt2',
        'custom_date_time_utc1' => 'getCustomDateTimeUtc1',
        'error_info' => 'getErrorInfo',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SHIPMENT_TYPE_ISSUE = 'Issue';
    public const SHIPMENT_TYPE_DROP_SHIP = 'DropShip';
    public const SHIPMENT_TYPE_TRANSFER = 'Transfer';
    public const STATUS_OPEN = 'Open';
    public const STATUS_HOLD = 'Hold';
    public const STATUS_COMPLETED = 'Completed';
    public const STATUS_CANCELLED = 'Cancelled';
    public const STATUS_CONFIRMED = 'Confirmed';
    public const STATUS_INVOICED = 'Invoiced';
    public const STATUS_RECEIPTED = 'Receipted';
    public const STATUS_AUTO_GENERATED = 'AutoGenerated';
    public const STATUS_PARTIALLY_INVOICED = 'PartiallyInvoiced';
    public const OPERATION_ISSUE = 'Issue';
    public const OPERATION_RECEIPT = 'Receipt';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getShipmentTypeAllowableValues()
    {
        return [
            self::SHIPMENT_TYPE_ISSUE,
            self::SHIPMENT_TYPE_DROP_SHIP,
            self::SHIPMENT_TYPE_TRANSFER,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_OPEN,
            self::STATUS_HOLD,
            self::STATUS_COMPLETED,
            self::STATUS_CANCELLED,
            self::STATUS_CONFIRMED,
            self::STATUS_INVOICED,
            self::STATUS_RECEIPTED,
            self::STATUS_AUTO_GENERATED,
            self::STATUS_PARTIALLY_INVOICED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOperationAllowableValues()
    {
        return [
            self::OPERATION_ISSUE,
            self::OPERATION_RECEIPT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('time_stamp', $data ?? [], null);
        $this->setIfExists('shipment_number', $data ?? [], null);
        $this->setIfExists('shipment_type', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('hold', $data ?? [], null);
        $this->setIfExists('operation', $data ?? [], null);
        $this->setIfExists('shipment_date', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('from_warehouse', $data ?? [], null);
        $this->setIfExists('to_warehouse', $data ?? [], null);
        $this->setIfExists('currency_id', $data ?? [], null);
        $this->setIfExists('owner', $data ?? [], null);
        $this->setIfExists('shipped_quantity', $data ?? [], null);
        $this->setIfExists('shipped_weight', $data ?? [], null);
        $this->setIfExists('shipped_volume', $data ?? [], null);
        $this->setIfExists('packages', $data ?? [], null);
        $this->setIfExists('packages_weight', $data ?? [], null);
        $this->setIfExists('packages_volume', $data ?? [], null);
        $this->setIfExists('control_quantity', $data ?? [], null);
        $this->setIfExists('delivery_address', $data ?? [], null);
        $this->setIfExists('delivery_contact', $data ?? [], null);
        $this->setIfExists('ship_via', $data ?? [], null);
        $this->setIfExists('fob_point', $data ?? [], null);
        $this->setIfExists('shipping_terms', $data ?? [], null);
        $this->setIfExists('shipping_zone', $data ?? [], null);
        $this->setIfExists('residential_delivery', $data ?? [], null);
        $this->setIfExists('saturday_delivery', $data ?? [], null);
        $this->setIfExists('use_customer_account', $data ?? [], null);
        $this->setIfExists('insurance', $data ?? [], null);
        $this->setIfExists('freight_cost', $data ?? [], null);
        $this->setIfExists('freight_amt', $data ?? [], null);
        $this->setIfExists('transaction_type', $data ?? [], null);
        $this->setIfExists('mode_of_trasport', $data ?? [], null);
        $this->setIfExists('container', $data ?? [], null);
        $this->setIfExists('shipment_detail_lines', $data ?? [], null);
        $this->setIfExists('shipment_order_lines', $data ?? [], null);
        $this->setIfExists('shipment_package_lines', $data ?? [], null);
        $this->setIfExists('last_modified_date_time', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('custom_str1', $data ?? [], null);
        $this->setIfExists('custom_str2', $data ?? [], null);
        $this->setIfExists('custom_str3', $data ?? [], null);
        $this->setIfExists('custom_str4', $data ?? [], null);
        $this->setIfExists('custom_str5', $data ?? [], null);
        $this->setIfExists('custom_dec1', $data ?? [], null);
        $this->setIfExists('custom_dec2', $data ?? [], null);
        $this->setIfExists('custom_int1', $data ?? [], null);
        $this->setIfExists('custom_int2', $data ?? [], null);
        $this->setIfExists('custom_date_time_utc1', $data ?? [], null);
        $this->setIfExists('error_info', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getShipmentTypeAllowableValues();
        if (!is_null($this->container['shipment_type']) && !in_array($this->container['shipment_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'shipment_type', must be one of '%s'",
                $this->container['shipment_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOperationAllowableValues();
        if (!is_null($this->container['operation']) && !in_array($this->container['operation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'operation', must be one of '%s'",
                $this->container['operation'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets time_stamp
     *
     * @return string|null
     */
    public function getTimeStamp()
    {
        return $this->container['time_stamp'];
    }

    /**
     * Sets time_stamp
     *
     * @param string|null $time_stamp time_stamp
     *
     * @return self
     */
    public function setTimeStamp($time_stamp)
    {
        if (is_null($time_stamp)) {
            throw new \InvalidArgumentException('non-nullable time_stamp cannot be null');
        }
        $this->container['time_stamp'] = $time_stamp;

        return $this;
    }

    /**
     * Gets shipment_number
     *
     * @return string|null
     */
    public function getShipmentNumber()
    {
        return $this->container['shipment_number'];
    }

    /**
     * Sets shipment_number
     *
     * @param string|null $shipment_number The top part &gt; Shipment no &gt; The unique reference number of the document, which is automatically generated by the system.
     *
     * @return self
     */
    public function setShipmentNumber($shipment_number)
    {
        if (is_null($shipment_number)) {
            throw new \InvalidArgumentException('non-nullable shipment_number cannot be null');
        }
        $this->container['shipment_number'] = $shipment_number;

        return $this;
    }

    /**
     * Gets shipment_type
     *
     * @return string|null
     */
    public function getShipmentType()
    {
        return $this->container['shipment_type'];
    }

    /**
     * Sets shipment_type
     *
     * @param string|null $shipment_type The top part &gt; Type &gt; The type of the shipment document, which can be one of the following options: Shipment, Transfer.
     *
     * @return self
     */
    public function setShipmentType($shipment_type)
    {
        if (is_null($shipment_type)) {
            throw new \InvalidArgumentException('non-nullable shipment_type cannot be null');
        }
        $allowedValues = $this->getShipmentTypeAllowableValues();
        if (!in_array($shipment_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'shipment_type', must be one of '%s'",
                    $shipment_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['shipment_type'] = $shipment_type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The top part &gt; Status &gt; The status of the document.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets hold
     *
     * @return bool|null
     */
    public function getHold()
    {
        return $this->container['hold'];
    }

    /**
     * Sets hold
     *
     * @param bool|null $hold The top part &gt; Hold &gt; This check box indicates (if selected) that the documents cannot be processed further until the check box is cleared.
     *
     * @return self
     */
    public function setHold($hold)
    {
        if (is_null($hold)) {
            throw new \InvalidArgumentException('non-nullable hold cannot be null');
        }
        $this->container['hold'] = $hold;

        return $this;
    }

    /**
     * Gets operation
     *
     * @return string|null
     */
    public function getOperation()
    {
        return $this->container['operation'];
    }

    /**
     * Sets operation
     *
     * @param string|null $operation The top part &gt; Operation &gt; The operation to be performed in the Inventory workspace for this shipment: Issue or Receipt.
     *
     * @return self
     */
    public function setOperation($operation)
    {
        if (is_null($operation)) {
            throw new \InvalidArgumentException('non-nullable operation cannot be null');
        }
        $allowedValues = $this->getOperationAllowableValues();
        if (!in_array($operation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'operation', must be one of '%s'",
                    $operation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['operation'] = $operation;

        return $this;
    }

    /**
     * Gets shipment_date
     *
     * @return \DateTime|null
     */
    public function getShipmentDate()
    {
        return $this->container['shipment_date'];
    }

    /**
     * Sets shipment_date
     *
     * @param \DateTime|null $shipment_date Mandatory field: The top part &gt; Shipment date* &gt; The date when the document has been created.
     *
     * @return self
     */
    public function setShipmentDate($shipment_date)
    {
        if (is_null($shipment_date)) {
            throw new \InvalidArgumentException('non-nullable shipment_date cannot be null');
        }
        $this->container['shipment_date'] = $shipment_date;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \OpenAPI\Client\Model\CustomerInShipmentDto|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \OpenAPI\Client\Model\CustomerInShipmentDto|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \OpenAPI\Client\Model\LocationInShipmentDto|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \OpenAPI\Client\Model\LocationInShipmentDto|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets from_warehouse
     *
     * @return \OpenAPI\Client\Model\FromWarehouseInShipmentDto|null
     */
    public function getFromWarehouse()
    {
        return $this->container['from_warehouse'];
    }

    /**
     * Sets from_warehouse
     *
     * @param \OpenAPI\Client\Model\FromWarehouseInShipmentDto|null $from_warehouse from_warehouse
     *
     * @return self
     */
    public function setFromWarehouse($from_warehouse)
    {
        if (is_null($from_warehouse)) {
            throw new \InvalidArgumentException('non-nullable from_warehouse cannot be null');
        }
        $this->container['from_warehouse'] = $from_warehouse;

        return $this;
    }

    /**
     * Gets to_warehouse
     *
     * @return \OpenAPI\Client\Model\ToWarehouseInShipmentDto|null
     */
    public function getToWarehouse()
    {
        return $this->container['to_warehouse'];
    }

    /**
     * Sets to_warehouse
     *
     * @param \OpenAPI\Client\Model\ToWarehouseInShipmentDto|null $to_warehouse to_warehouse
     *
     * @return self
     */
    public function setToWarehouse($to_warehouse)
    {
        if (is_null($to_warehouse)) {
            throw new \InvalidArgumentException('non-nullable to_warehouse cannot be null');
        }
        $this->container['to_warehouse'] = $to_warehouse;

        return $this;
    }

    /**
     * Gets currency_id
     *
     * @return string|null
     */
    public function getCurrencyId()
    {
        return $this->container['currency_id'];
    }

    /**
     * Sets currency_id
     *
     * @param string|null $currency_id Delivery settings tab &gt; Freight currency &gt; By default, it is the currency of the sales order, but you can change it if needed.
     *
     * @return self
     */
    public function setCurrencyId($currency_id)
    {
        if (is_null($currency_id)) {
            throw new \InvalidArgumentException('non-nullable currency_id cannot be null');
        }
        $this->container['currency_id'] = $currency_id;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return \OpenAPI\Client\Model\OwnerInShipmentDto|null
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param \OpenAPI\Client\Model\OwnerInShipmentDto|null $owner owner
     *
     * @return self
     */
    public function setOwner($owner)
    {
        if (is_null($owner)) {
            throw new \InvalidArgumentException('non-nullable owner cannot be null');
        }
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets shipped_quantity
     *
     * @return float|null
     */
    public function getShippedQuantity()
    {
        return $this->container['shipped_quantity'];
    }

    /**
     * Sets shipped_quantity
     *
     * @param float|null $shipped_quantity The top part &gt; Shipped quantity &gt; The quantity of goods shipped.
     *
     * @return self
     */
    public function setShippedQuantity($shipped_quantity)
    {
        if (is_null($shipped_quantity)) {
            throw new \InvalidArgumentException('non-nullable shipped_quantity cannot be null');
        }
        $this->container['shipped_quantity'] = $shipped_quantity;

        return $this;
    }

    /**
     * Gets shipped_weight
     *
     * @return float|null
     */
    public function getShippedWeight()
    {
        return $this->container['shipped_weight'];
    }

    /**
     * Sets shipped_weight
     *
     * @param float|null $shipped_weight The top part &gt; Shipped weight &gt; The weight of the goods shipped.
     *
     * @return self
     */
    public function setShippedWeight($shipped_weight)
    {
        if (is_null($shipped_weight)) {
            throw new \InvalidArgumentException('non-nullable shipped_weight cannot be null');
        }
        $this->container['shipped_weight'] = $shipped_weight;

        return $this;
    }

    /**
     * Gets shipped_volume
     *
     * @return float|null
     */
    public function getShippedVolume()
    {
        return $this->container['shipped_volume'];
    }

    /**
     * Sets shipped_volume
     *
     * @param float|null $shipped_volume The top part &gt; Shipped volume &gt; The total volume of the items in the shipment.
     *
     * @return self
     */
    public function setShippedVolume($shipped_volume)
    {
        if (is_null($shipped_volume)) {
            throw new \InvalidArgumentException('non-nullable shipped_volume cannot be null');
        }
        $this->container['shipped_volume'] = $shipped_volume;

        return $this;
    }

    /**
     * Gets packages
     *
     * @return int|null
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     *
     * @param int|null $packages The top part &gt; Packages &gt; The number of boxes included in this shipment.
     *
     * @return self
     */
    public function setPackages($packages)
    {
        if (is_null($packages)) {
            throw new \InvalidArgumentException('non-nullable packages cannot be null');
        }
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Gets packages_weight
     *
     * @return float|null
     */
    public function getPackagesWeight()
    {
        return $this->container['packages_weight'];
    }

    /**
     * Sets packages_weight
     *
     * @param float|null $packages_weight The top part &gt; Package weight &gt; The total weight of the shipment that includes the weight of boxes (for boxes determined automatically).
     *
     * @return self
     */
    public function setPackagesWeight($packages_weight)
    {
        if (is_null($packages_weight)) {
            throw new \InvalidArgumentException('non-nullable packages_weight cannot be null');
        }
        $this->container['packages_weight'] = $packages_weight;

        return $this;
    }

    /**
     * Gets packages_volume
     *
     * @return float|null
     */
    public function getPackagesVolume()
    {
        return $this->container['packages_volume'];
    }

    /**
     * Sets packages_volume
     *
     * @param float|null $packages_volume The top part &gt; Package volume &gt; The total volume of the shipment that includes the volume of boxes (for boxes determined automatically).
     *
     * @return self
     */
    public function setPackagesVolume($packages_volume)
    {
        if (is_null($packages_volume)) {
            throw new \InvalidArgumentException('non-nullable packages_volume cannot be null');
        }
        $this->container['packages_volume'] = $packages_volume;

        return $this;
    }

    /**
     * Gets control_quantity
     *
     * @return float|null
     */
    public function getControlQuantity()
    {
        return $this->container['control_quantity'];
    }

    /**
     * Sets control_quantity
     *
     * @param float|null $control_quantity The top part &gt; Control quantity &gt; The control value, which you manually enter as a value equal to the shipped quantity if the Validate shipment total on confirmation check box has been selected in the Sales orders preferences (SO101000) window.
     *
     * @return self
     */
    public function setControlQuantity($control_quantity)
    {
        if (is_null($control_quantity)) {
            throw new \InvalidArgumentException('non-nullable control_quantity cannot be null');
        }
        $this->container['control_quantity'] = $control_quantity;

        return $this;
    }

    /**
     * Gets delivery_address
     *
     * @return \OpenAPI\Client\Model\DeliveryAddressInShipmentDto|null
     */
    public function getDeliveryAddress()
    {
        return $this->container['delivery_address'];
    }

    /**
     * Sets delivery_address
     *
     * @param \OpenAPI\Client\Model\DeliveryAddressInShipmentDto|null $delivery_address delivery_address
     *
     * @return self
     */
    public function setDeliveryAddress($delivery_address)
    {
        if (is_null($delivery_address)) {
            throw new \InvalidArgumentException('non-nullable delivery_address cannot be null');
        }
        $this->container['delivery_address'] = $delivery_address;

        return $this;
    }

    /**
     * Gets delivery_contact
     *
     * @return \OpenAPI\Client\Model\DeliveryContactInShipmentDto|null
     */
    public function getDeliveryContact()
    {
        return $this->container['delivery_contact'];
    }

    /**
     * Sets delivery_contact
     *
     * @param \OpenAPI\Client\Model\DeliveryContactInShipmentDto|null $delivery_contact delivery_contact
     *
     * @return self
     */
    public function setDeliveryContact($delivery_contact)
    {
        if (is_null($delivery_contact)) {
            throw new \InvalidArgumentException('non-nullable delivery_contact cannot be null');
        }
        $this->container['delivery_contact'] = $delivery_contact;

        return $this;
    }

    /**
     * Gets ship_via
     *
     * @return \OpenAPI\Client\Model\ShipViaInShipmentDto|null
     */
    public function getShipVia()
    {
        return $this->container['ship_via'];
    }

    /**
     * Sets ship_via
     *
     * @param \OpenAPI\Client\Model\ShipViaInShipmentDto|null $ship_via ship_via
     *
     * @return self
     */
    public function setShipVia($ship_via)
    {
        if (is_null($ship_via)) {
            throw new \InvalidArgumentException('non-nullable ship_via cannot be null');
        }
        $this->container['ship_via'] = $ship_via;

        return $this;
    }

    /**
     * Gets fob_point
     *
     * @return \OpenAPI\Client\Model\FobPointInShipmentDto|null
     */
    public function getFobPoint()
    {
        return $this->container['fob_point'];
    }

    /**
     * Sets fob_point
     *
     * @param \OpenAPI\Client\Model\FobPointInShipmentDto|null $fob_point fob_point
     *
     * @return self
     */
    public function setFobPoint($fob_point)
    {
        if (is_null($fob_point)) {
            throw new \InvalidArgumentException('non-nullable fob_point cannot be null');
        }
        $this->container['fob_point'] = $fob_point;

        return $this;
    }

    /**
     * Gets shipping_terms
     *
     * @return \OpenAPI\Client\Model\ShippingTermsInShipmentDto|null
     */
    public function getShippingTerms()
    {
        return $this->container['shipping_terms'];
    }

    /**
     * Sets shipping_terms
     *
     * @param \OpenAPI\Client\Model\ShippingTermsInShipmentDto|null $shipping_terms shipping_terms
     *
     * @return self
     */
    public function setShippingTerms($shipping_terms)
    {
        if (is_null($shipping_terms)) {
            throw new \InvalidArgumentException('non-nullable shipping_terms cannot be null');
        }
        $this->container['shipping_terms'] = $shipping_terms;

        return $this;
    }

    /**
     * Gets shipping_zone
     *
     * @return \OpenAPI\Client\Model\ShippingZoneInShipmentDto|null
     */
    public function getShippingZone()
    {
        return $this->container['shipping_zone'];
    }

    /**
     * Sets shipping_zone
     *
     * @param \OpenAPI\Client\Model\ShippingZoneInShipmentDto|null $shipping_zone shipping_zone
     *
     * @return self
     */
    public function setShippingZone($shipping_zone)
    {
        if (is_null($shipping_zone)) {
            throw new \InvalidArgumentException('non-nullable shipping_zone cannot be null');
        }
        $this->container['shipping_zone'] = $shipping_zone;

        return $this;
    }

    /**
     * Gets residential_delivery
     *
     * @return bool|null
     */
    public function getResidentialDelivery()
    {
        return $this->container['residential_delivery'];
    }

    /**
     * Sets residential_delivery
     *
     * @param bool|null $residential_delivery Delivery settings tab &gt; Shipping information section &gt; Residential delivery &gt; This check box indicates (if selected) that the shipping address is a residential one.
     *
     * @return self
     */
    public function setResidentialDelivery($residential_delivery)
    {
        if (is_null($residential_delivery)) {
            throw new \InvalidArgumentException('non-nullable residential_delivery cannot be null');
        }
        $this->container['residential_delivery'] = $residential_delivery;

        return $this;
    }

    /**
     * Gets saturday_delivery
     *
     * @return bool|null
     */
    public function getSaturdayDelivery()
    {
        return $this->container['saturday_delivery'];
    }

    /**
     * Sets saturday_delivery
     *
     * @param bool|null $saturday_delivery Delivery settings tab &gt; Shipping information section &gt; Saturday delivery &gt; This check box indicates delivery on saturday.
     *
     * @return self
     */
    public function setSaturdayDelivery($saturday_delivery)
    {
        if (is_null($saturday_delivery)) {
            throw new \InvalidArgumentException('non-nullable saturday_delivery cannot be null');
        }
        $this->container['saturday_delivery'] = $saturday_delivery;

        return $this;
    }

    /**
     * Gets use_customer_account
     *
     * @return bool|null
     */
    public function getUseCustomerAccount()
    {
        return $this->container['use_customer_account'];
    }

    /**
     * Sets use_customer_account
     *
     * @param bool|null $use_customer_account use_customer_account
     *
     * @return self
     */
    public function setUseCustomerAccount($use_customer_account)
    {
        if (is_null($use_customer_account)) {
            throw new \InvalidArgumentException('non-nullable use_customer_account cannot be null');
        }
        $this->container['use_customer_account'] = $use_customer_account;

        return $this;
    }

    /**
     * Gets insurance
     *
     * @return bool|null
     */
    public function getInsurance()
    {
        return $this->container['insurance'];
    }

    /**
     * Sets insurance
     *
     * @param bool|null $insurance Delivery settings tab &gt; Shipping information section &gt; Insurance &gt; This check box indicates (if selected) that insurance is required for the shipment.
     *
     * @return self
     */
    public function setInsurance($insurance)
    {
        if (is_null($insurance)) {
            throw new \InvalidArgumentException('non-nullable insurance cannot be null');
        }
        $this->container['insurance'] = $insurance;

        return $this;
    }

    /**
     * Gets freight_cost
     *
     * @return float|null
     */
    public function getFreightCost()
    {
        return $this->container['freight_cost'];
    }

    /**
     * Sets freight_cost
     *
     * @param float|null $freight_cost Delivery settings tab &gt; Shipping information section &gt; Freight cost &gt; The freight cost of the shipment.
     *
     * @return self
     */
    public function setFreightCost($freight_cost)
    {
        if (is_null($freight_cost)) {
            throw new \InvalidArgumentException('non-nullable freight_cost cannot be null');
        }
        $this->container['freight_cost'] = $freight_cost;

        return $this;
    }

    /**
     * Gets freight_amt
     *
     * @return float|null
     */
    public function getFreightAmt()
    {
        return $this->container['freight_amt'];
    }

    /**
     * Sets freight_amt
     *
     * @param float|null $freight_amt Delivery settings tab &gt; Shipping information section &gt; Freight amt. &gt; The amount of freight the customer will be charged for the shipment.
     *
     * @return self
     */
    public function setFreightAmt($freight_amt)
    {
        if (is_null($freight_amt)) {
            throw new \InvalidArgumentException('non-nullable freight_amt cannot be null');
        }
        $this->container['freight_amt'] = $freight_amt;

        return $this;
    }

    /**
     * Gets transaction_type
     *
     * @return \OpenAPI\Client\Model\TransactionTypeInShipmentDto|null
     */
    public function getTransactionType()
    {
        return $this->container['transaction_type'];
    }

    /**
     * Sets transaction_type
     *
     * @param \OpenAPI\Client\Model\TransactionTypeInShipmentDto|null $transaction_type transaction_type
     *
     * @return self
     */
    public function setTransactionType($transaction_type)
    {
        if (is_null($transaction_type)) {
            throw new \InvalidArgumentException('non-nullable transaction_type cannot be null');
        }
        $this->container['transaction_type'] = $transaction_type;

        return $this;
    }

    /**
     * Gets mode_of_trasport
     *
     * @return \OpenAPI\Client\Model\ModeOfTrasportInShipmentDto|null
     */
    public function getModeOfTrasport()
    {
        return $this->container['mode_of_trasport'];
    }

    /**
     * Sets mode_of_trasport
     *
     * @param \OpenAPI\Client\Model\ModeOfTrasportInShipmentDto|null $mode_of_trasport mode_of_trasport
     *
     * @return self
     */
    public function setModeOfTrasport($mode_of_trasport)
    {
        if (is_null($mode_of_trasport)) {
            throw new \InvalidArgumentException('non-nullable mode_of_trasport cannot be null');
        }
        $this->container['mode_of_trasport'] = $mode_of_trasport;

        return $this;
    }

    /**
     * Gets container
     *
     * @return bool|null
     */
    public function getContainer()
    {
        return $this->container['container'];
    }

    /**
     * Sets container
     *
     * @param bool|null $container Delivery settings tab &gt; Intrastat section &gt; Container &gt; This check box indicates (if selected) that the shipment gets marked as shipped in container for Intrastat reporting purposes.
     *
     * @return self
     */
    public function setContainer($container)
    {
        if (is_null($container)) {
            throw new \InvalidArgumentException('non-nullable container cannot be null');
        }
        $this->container['container'] = $container;

        return $this;
    }

    /**
     * Gets shipment_detail_lines
     *
     * @return \OpenAPI\Client\Model\ShipmentDetailLineDto[]|null
     */
    public function getShipmentDetailLines()
    {
        return $this->container['shipment_detail_lines'];
    }

    /**
     * Sets shipment_detail_lines
     *
     * @param \OpenAPI\Client\Model\ShipmentDetailLineDto[]|null $shipment_detail_lines Document details tab &gt;
     *
     * @return self
     */
    public function setShipmentDetailLines($shipment_detail_lines)
    {
        if (is_null($shipment_detail_lines)) {
            throw new \InvalidArgumentException('non-nullable shipment_detail_lines cannot be null');
        }
        $this->container['shipment_detail_lines'] = $shipment_detail_lines;

        return $this;
    }

    /**
     * Gets shipment_order_lines
     *
     * @return \OpenAPI\Client\Model\ShipmentOrderLineDto[]|null
     */
    public function getShipmentOrderLines()
    {
        return $this->container['shipment_order_lines'];
    }

    /**
     * Sets shipment_order_lines
     *
     * @param \OpenAPI\Client\Model\ShipmentOrderLineDto[]|null $shipment_order_lines Orders tab &gt;
     *
     * @return self
     */
    public function setShipmentOrderLines($shipment_order_lines)
    {
        if (is_null($shipment_order_lines)) {
            throw new \InvalidArgumentException('non-nullable shipment_order_lines cannot be null');
        }
        $this->container['shipment_order_lines'] = $shipment_order_lines;

        return $this;
    }

    /**
     * Gets shipment_package_lines
     *
     * @return \OpenAPI\Client\Model\PackageDetailLineDto[]|null
     */
    public function getShipmentPackageLines()
    {
        return $this->container['shipment_package_lines'];
    }

    /**
     * Sets shipment_package_lines
     *
     * @param \OpenAPI\Client\Model\PackageDetailLineDto[]|null $shipment_package_lines Packages tab &gt;
     *
     * @return self
     */
    public function setShipmentPackageLines($shipment_package_lines)
    {
        if (is_null($shipment_package_lines)) {
            throw new \InvalidArgumentException('non-nullable shipment_package_lines cannot be null');
        }
        $this->container['shipment_package_lines'] = $shipment_package_lines;

        return $this;
    }

    /**
     * Gets last_modified_date_time
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDateTime()
    {
        return $this->container['last_modified_date_time'];
    }

    /**
     * Sets last_modified_date_time
     *
     * @param \DateTime|null $last_modified_date_time System generated information.
     *
     * @return self
     */
    public function setLastModifiedDateTime($last_modified_date_time)
    {
        if (is_null($last_modified_date_time)) {
            throw new \InvalidArgumentException('non-nullable last_modified_date_time cannot be null');
        }
        $this->container['last_modified_date_time'] = $last_modified_date_time;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            throw new \InvalidArgumentException('non-nullable note cannot be null');
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets custom_str1
     *
     * @return string|null
     */
    public function getCustomStr1()
    {
        return $this->container['custom_str1'];
    }

    /**
     * Sets custom_str1
     *
     * @param string|null $custom_str1 A free custom colum of type string with max length 100.
     *
     * @return self
     */
    public function setCustomStr1($custom_str1)
    {
        if (is_null($custom_str1)) {
            throw new \InvalidArgumentException('non-nullable custom_str1 cannot be null');
        }
        $this->container['custom_str1'] = $custom_str1;

        return $this;
    }

    /**
     * Gets custom_str2
     *
     * @return string|null
     */
    public function getCustomStr2()
    {
        return $this->container['custom_str2'];
    }

    /**
     * Sets custom_str2
     *
     * @param string|null $custom_str2 A free custom colum of type string with max length 100.
     *
     * @return self
     */
    public function setCustomStr2($custom_str2)
    {
        if (is_null($custom_str2)) {
            throw new \InvalidArgumentException('non-nullable custom_str2 cannot be null');
        }
        $this->container['custom_str2'] = $custom_str2;

        return $this;
    }

    /**
     * Gets custom_str3
     *
     * @return string|null
     */
    public function getCustomStr3()
    {
        return $this->container['custom_str3'];
    }

    /**
     * Sets custom_str3
     *
     * @param string|null $custom_str3 A free custom colum of type string with max length 100.
     *
     * @return self
     */
    public function setCustomStr3($custom_str3)
    {
        if (is_null($custom_str3)) {
            throw new \InvalidArgumentException('non-nullable custom_str3 cannot be null');
        }
        $this->container['custom_str3'] = $custom_str3;

        return $this;
    }

    /**
     * Gets custom_str4
     *
     * @return string|null
     */
    public function getCustomStr4()
    {
        return $this->container['custom_str4'];
    }

    /**
     * Sets custom_str4
     *
     * @param string|null $custom_str4 A free custom colum of type string with max length 100.
     *
     * @return self
     */
    public function setCustomStr4($custom_str4)
    {
        if (is_null($custom_str4)) {
            throw new \InvalidArgumentException('non-nullable custom_str4 cannot be null');
        }
        $this->container['custom_str4'] = $custom_str4;

        return $this;
    }

    /**
     * Gets custom_str5
     *
     * @return string|null
     */
    public function getCustomStr5()
    {
        return $this->container['custom_str5'];
    }

    /**
     * Sets custom_str5
     *
     * @param string|null $custom_str5 A free custom colum of type string with max length 100.
     *
     * @return self
     */
    public function setCustomStr5($custom_str5)
    {
        if (is_null($custom_str5)) {
            throw new \InvalidArgumentException('non-nullable custom_str5 cannot be null');
        }
        $this->container['custom_str5'] = $custom_str5;

        return $this;
    }

    /**
     * Gets custom_dec1
     *
     * @return float|null
     */
    public function getCustomDec1()
    {
        return $this->container['custom_dec1'];
    }

    /**
     * Sets custom_dec1
     *
     * @param float|null $custom_dec1 A free custom colum of type decimal with max 4 decimals.
     *
     * @return self
     */
    public function setCustomDec1($custom_dec1)
    {
        if (is_null($custom_dec1)) {
            throw new \InvalidArgumentException('non-nullable custom_dec1 cannot be null');
        }
        $this->container['custom_dec1'] = $custom_dec1;

        return $this;
    }

    /**
     * Gets custom_dec2
     *
     * @return float|null
     */
    public function getCustomDec2()
    {
        return $this->container['custom_dec2'];
    }

    /**
     * Sets custom_dec2
     *
     * @param float|null $custom_dec2 A free custom colum of type decimal with max 4 decimals.
     *
     * @return self
     */
    public function setCustomDec2($custom_dec2)
    {
        if (is_null($custom_dec2)) {
            throw new \InvalidArgumentException('non-nullable custom_dec2 cannot be null');
        }
        $this->container['custom_dec2'] = $custom_dec2;

        return $this;
    }

    /**
     * Gets custom_int1
     *
     * @return int|null
     */
    public function getCustomInt1()
    {
        return $this->container['custom_int1'];
    }

    /**
     * Sets custom_int1
     *
     * @param int|null $custom_int1 A free custom colum of type int
     *
     * @return self
     */
    public function setCustomInt1($custom_int1)
    {
        if (is_null($custom_int1)) {
            throw new \InvalidArgumentException('non-nullable custom_int1 cannot be null');
        }
        $this->container['custom_int1'] = $custom_int1;

        return $this;
    }

    /**
     * Gets custom_int2
     *
     * @return int|null
     */
    public function getCustomInt2()
    {
        return $this->container['custom_int2'];
    }

    /**
     * Sets custom_int2
     *
     * @param int|null $custom_int2 A free custom colum of type int
     *
     * @return self
     */
    public function setCustomInt2($custom_int2)
    {
        if (is_null($custom_int2)) {
            throw new \InvalidArgumentException('non-nullable custom_int2 cannot be null');
        }
        $this->container['custom_int2'] = $custom_int2;

        return $this;
    }

    /**
     * Gets custom_date_time_utc1
     *
     * @return \DateTime|null
     */
    public function getCustomDateTimeUtc1()
    {
        return $this->container['custom_date_time_utc1'];
    }

    /**
     * Sets custom_date_time_utc1
     *
     * @param \DateTime|null $custom_date_time_utc1 A free custom colum of type DateTime - in UTC timezone
     *
     * @return self
     */
    public function setCustomDateTimeUtc1($custom_date_time_utc1)
    {
        if (is_null($custom_date_time_utc1)) {
            throw new \InvalidArgumentException('non-nullable custom_date_time_utc1 cannot be null');
        }
        $this->container['custom_date_time_utc1'] = $custom_date_time_utc1;

        return $this;
    }

    /**
     * Gets error_info
     *
     * @return string|null
     */
    public function getErrorInfo()
    {
        return $this->container['error_info'];
    }

    /**
     * Sets error_info
     *
     * @param string|null $error_info error_info
     *
     * @return self
     */
    public function setErrorInfo($error_info)
    {
        if (is_null($error_info)) {
            throw new \InvalidArgumentException('non-nullable error_info cannot be null');
        }
        $this->container['error_info'] = $error_info;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return \OpenAPI\Client\Model\MetadataDto|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param \OpenAPI\Client\Model\MetadataDto|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


