<?php
/**
 * ShipmentOrderLineDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShipmentOrderLineDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentOrderLineDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentOrderLineDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'order_type' => 'string',
        'order_nbr' => 'string',
        'shipped_qty' => 'float',
        'shipped_weight' => 'float',
        'shipped_volume' => 'float',
        'invoice_type' => 'string',
        'invoice_nbr' => 'string',
        'inventory_doc_type' => 'string',
        'inventory_ref_nbr' => 'string',
        'note' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'order_type' => null,
        'order_nbr' => null,
        'shipped_qty' => 'double',
        'shipped_weight' => 'double',
        'shipped_volume' => 'double',
        'invoice_type' => null,
        'invoice_nbr' => null,
        'inventory_doc_type' => null,
        'inventory_ref_nbr' => null,
        'note' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'order_type' => false,
        'order_nbr' => false,
        'shipped_qty' => false,
        'shipped_weight' => false,
        'shipped_volume' => false,
        'invoice_type' => false,
        'invoice_nbr' => false,
        'inventory_doc_type' => false,
        'inventory_ref_nbr' => false,
        'note' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_type' => 'orderType',
        'order_nbr' => 'orderNbr',
        'shipped_qty' => 'shippedQty',
        'shipped_weight' => 'shippedWeight',
        'shipped_volume' => 'shippedVolume',
        'invoice_type' => 'invoiceType',
        'invoice_nbr' => 'invoiceNbr',
        'inventory_doc_type' => 'inventoryDocType',
        'inventory_ref_nbr' => 'inventoryRefNbr',
        'note' => 'note'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_type' => 'setOrderType',
        'order_nbr' => 'setOrderNbr',
        'shipped_qty' => 'setShippedQty',
        'shipped_weight' => 'setShippedWeight',
        'shipped_volume' => 'setShippedVolume',
        'invoice_type' => 'setInvoiceType',
        'invoice_nbr' => 'setInvoiceNbr',
        'inventory_doc_type' => 'setInventoryDocType',
        'inventory_ref_nbr' => 'setInventoryRefNbr',
        'note' => 'setNote'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_type' => 'getOrderType',
        'order_nbr' => 'getOrderNbr',
        'shipped_qty' => 'getShippedQty',
        'shipped_weight' => 'getShippedWeight',
        'shipped_volume' => 'getShippedVolume',
        'invoice_type' => 'getInvoiceType',
        'invoice_nbr' => 'getInvoiceNbr',
        'inventory_doc_type' => 'getInventoryDocType',
        'inventory_ref_nbr' => 'getInventoryRefNbr',
        'note' => 'getNote'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('order_type', $data ?? [], null);
        $this->setIfExists('order_nbr', $data ?? [], null);
        $this->setIfExists('shipped_qty', $data ?? [], null);
        $this->setIfExists('shipped_weight', $data ?? [], null);
        $this->setIfExists('shipped_volume', $data ?? [], null);
        $this->setIfExists('invoice_type', $data ?? [], null);
        $this->setIfExists('invoice_nbr', $data ?? [], null);
        $this->setIfExists('inventory_doc_type', $data ?? [], null);
        $this->setIfExists('inventory_ref_nbr', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_type
     *
     * @return string|null
     */
    public function getOrderType()
    {
        return $this->container['order_type'];
    }

    /**
     * Sets order_type
     *
     * @param string|null $order_type Orders tab &gt; Order typer &gt; The type of the order.
     *
     * @return self
     */
    public function setOrderType($order_type)
    {
        if (is_null($order_type)) {
            throw new \InvalidArgumentException('non-nullable order_type cannot be null');
        }
        $this->container['order_type'] = $order_type;

        return $this;
    }

    /**
     * Gets order_nbr
     *
     * @return string|null
     */
    public function getOrderNbr()
    {
        return $this->container['order_nbr'];
    }

    /**
     * Sets order_nbr
     *
     * @param string|null $order_nbr Orders tab &gt; Order no. &gt; The reference number of the sales or transfer order.
     *
     * @return self
     */
    public function setOrderNbr($order_nbr)
    {
        if (is_null($order_nbr)) {
            throw new \InvalidArgumentException('non-nullable order_nbr cannot be null');
        }
        $this->container['order_nbr'] = $order_nbr;

        return $this;
    }

    /**
     * Gets shipped_qty
     *
     * @return float|null
     */
    public function getShippedQty()
    {
        return $this->container['shipped_qty'];
    }

    /**
     * Sets shipped_qty
     *
     * @param float|null $shipped_qty Orders tab &gt; Shipped qty. &gt; The quantity of goods shipped in accordance with the order.
     *
     * @return self
     */
    public function setShippedQty($shipped_qty)
    {
        if (is_null($shipped_qty)) {
            throw new \InvalidArgumentException('non-nullable shipped_qty cannot be null');
        }
        $this->container['shipped_qty'] = $shipped_qty;

        return $this;
    }

    /**
     * Gets shipped_weight
     *
     * @return float|null
     */
    public function getShippedWeight()
    {
        return $this->container['shipped_weight'];
    }

    /**
     * Sets shipped_weight
     *
     * @param float|null $shipped_weight Orders tab &gt; Shipped weight &gt; The weight of the goods shipped in accordance with the order.
     *
     * @return self
     */
    public function setShippedWeight($shipped_weight)
    {
        if (is_null($shipped_weight)) {
            throw new \InvalidArgumentException('non-nullable shipped_weight cannot be null');
        }
        $this->container['shipped_weight'] = $shipped_weight;

        return $this;
    }

    /**
     * Gets shipped_volume
     *
     * @return float|null
     */
    public function getShippedVolume()
    {
        return $this->container['shipped_volume'];
    }

    /**
     * Sets shipped_volume
     *
     * @param float|null $shipped_volume Orders tab &gt; Shipped volume &gt; The volume of the goods shipped in accordance with the sales or transfer order.
     *
     * @return self
     */
    public function setShippedVolume($shipped_volume)
    {
        if (is_null($shipped_volume)) {
            throw new \InvalidArgumentException('non-nullable shipped_volume cannot be null');
        }
        $this->container['shipped_volume'] = $shipped_volume;

        return $this;
    }

    /**
     * Gets invoice_type
     *
     * @return string|null
     */
    public function getInvoiceType()
    {
        return $this->container['invoice_type'];
    }

    /**
     * Sets invoice_type
     *
     * @param string|null $invoice_type Orders tab &gt; Invoice type &gt; The type of invoice for the goods shipped for the sales order.
     *
     * @return self
     */
    public function setInvoiceType($invoice_type)
    {
        if (is_null($invoice_type)) {
            throw new \InvalidArgumentException('non-nullable invoice_type cannot be null');
        }
        $this->container['invoice_type'] = $invoice_type;

        return $this;
    }

    /**
     * Gets invoice_nbr
     *
     * @return string|null
     */
    public function getInvoiceNbr()
    {
        return $this->container['invoice_nbr'];
    }

    /**
     * Sets invoice_nbr
     *
     * @param string|null $invoice_nbr Orders tab &gt; Invoice no. &gt; The reference number of the invoice for the goods shipped.
     *
     * @return self
     */
    public function setInvoiceNbr($invoice_nbr)
    {
        if (is_null($invoice_nbr)) {
            throw new \InvalidArgumentException('non-nullable invoice_nbr cannot be null');
        }
        $this->container['invoice_nbr'] = $invoice_nbr;

        return $this;
    }

    /**
     * Gets inventory_doc_type
     *
     * @return string|null
     */
    public function getInventoryDocType()
    {
        return $this->container['inventory_doc_type'];
    }

    /**
     * Sets inventory_doc_type
     *
     * @param string|null $inventory_doc_type Orders tab &gt; Inventory doc. type &gt; The type of the inventory document that lists the items for this shipment.
     *
     * @return self
     */
    public function setInventoryDocType($inventory_doc_type)
    {
        if (is_null($inventory_doc_type)) {
            throw new \InvalidArgumentException('non-nullable inventory_doc_type cannot be null');
        }
        $this->container['inventory_doc_type'] = $inventory_doc_type;

        return $this;
    }

    /**
     * Gets inventory_ref_nbr
     *
     * @return string|null
     */
    public function getInventoryRefNbr()
    {
        return $this->container['inventory_ref_nbr'];
    }

    /**
     * Sets inventory_ref_nbr
     *
     * @param string|null $inventory_ref_nbr Orders tab &gt; Inventory ref. no. &gt; The reference number of the inventory document that lists the items for this shipment.
     *
     * @return self
     */
    public function setInventoryRefNbr($inventory_ref_nbr)
    {
        if (is_null($inventory_ref_nbr)) {
            throw new \InvalidArgumentException('non-nullable inventory_ref_nbr cannot be null');
        }
        $this->container['inventory_ref_nbr'] = $inventory_ref_nbr;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            throw new \InvalidArgumentException('non-nullable note cannot be null');
        }
        $this->container['note'] = $note;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


