<?php
/**
 * ShipmentDetailLineAddDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShipmentDetailLineAddDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentDetailLineAddDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentDetailLineAddDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'operation' => 'string',
        'inventory_number' => '\OpenAPI\Client\Model\DtoValueOfString',
        'line_number' => '\OpenAPI\Client\Model\DtoValueOfInt32',
        'warehouse' => '\OpenAPI\Client\Model\DtoValueOfString',
        'location' => '\OpenAPI\Client\Model\DtoValueOfString',
        'uom' => '\OpenAPI\Client\Model\DtoValueOfString',
        'shipped_qty' => '\OpenAPI\Client\Model\DtoValueOfNullableOfDecimal',
        'custom_str1' => '\OpenAPI\Client\Model\CustomStr1InShipmentDetailLineAddDto',
        'custom_str2' => '\OpenAPI\Client\Model\CustomStr2InShipmentDetailLineAddDto',
        'custom_str3' => '\OpenAPI\Client\Model\CustomStr3InShipmentDetailLineAddDto',
        'custom_str4' => '\OpenAPI\Client\Model\CustomStr4InShipmentDetailLineAddDto',
        'custom_str5' => '\OpenAPI\Client\Model\CustomStr5InShipmentDetailLineAddDto',
        'custom_dec1' => '\OpenAPI\Client\Model\CustomDec1InShipmentDetailLineAddDto',
        'custom_dec2' => '\OpenAPI\Client\Model\CustomDec2InShipmentDetailLineAddDto',
        'custom_int1' => '\OpenAPI\Client\Model\CustomInt1InShipmentDetailLineAddDto',
        'custom_int2' => '\OpenAPI\Client\Model\CustomInt2InShipmentDetailLineAddDto',
        'custom_date_time_utc1' => '\OpenAPI\Client\Model\CustomDateTimeUTC1InShipmentDetailLineAddDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'operation' => null,
        'inventory_number' => null,
        'line_number' => null,
        'warehouse' => null,
        'location' => null,
        'uom' => null,
        'shipped_qty' => null,
        'custom_str1' => null,
        'custom_str2' => null,
        'custom_str3' => null,
        'custom_str4' => null,
        'custom_str5' => null,
        'custom_dec1' => null,
        'custom_dec2' => null,
        'custom_int1' => null,
        'custom_int2' => null,
        'custom_date_time_utc1' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'operation' => false,
        'inventory_number' => false,
        'line_number' => false,
        'warehouse' => false,
        'location' => false,
        'uom' => false,
        'shipped_qty' => false,
        'custom_str1' => false,
        'custom_str2' => false,
        'custom_str3' => false,
        'custom_str4' => false,
        'custom_str5' => false,
        'custom_dec1' => false,
        'custom_dec2' => false,
        'custom_int1' => false,
        'custom_int2' => false,
        'custom_date_time_utc1' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'operation' => 'operation',
        'inventory_number' => 'inventoryNumber',
        'line_number' => 'lineNumber',
        'warehouse' => 'warehouse',
        'location' => 'location',
        'uom' => 'uom',
        'shipped_qty' => 'shippedQty',
        'custom_str1' => 'customStr1',
        'custom_str2' => 'customStr2',
        'custom_str3' => 'customStr3',
        'custom_str4' => 'customStr4',
        'custom_str5' => 'customStr5',
        'custom_dec1' => 'customDec1',
        'custom_dec2' => 'customDec2',
        'custom_int1' => 'customInt1',
        'custom_int2' => 'customInt2',
        'custom_date_time_utc1' => 'customDateTimeUTC1'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'operation' => 'setOperation',
        'inventory_number' => 'setInventoryNumber',
        'line_number' => 'setLineNumber',
        'warehouse' => 'setWarehouse',
        'location' => 'setLocation',
        'uom' => 'setUom',
        'shipped_qty' => 'setShippedQty',
        'custom_str1' => 'setCustomStr1',
        'custom_str2' => 'setCustomStr2',
        'custom_str3' => 'setCustomStr3',
        'custom_str4' => 'setCustomStr4',
        'custom_str5' => 'setCustomStr5',
        'custom_dec1' => 'setCustomDec1',
        'custom_dec2' => 'setCustomDec2',
        'custom_int1' => 'setCustomInt1',
        'custom_int2' => 'setCustomInt2',
        'custom_date_time_utc1' => 'setCustomDateTimeUtc1'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'operation' => 'getOperation',
        'inventory_number' => 'getInventoryNumber',
        'line_number' => 'getLineNumber',
        'warehouse' => 'getWarehouse',
        'location' => 'getLocation',
        'uom' => 'getUom',
        'shipped_qty' => 'getShippedQty',
        'custom_str1' => 'getCustomStr1',
        'custom_str2' => 'getCustomStr2',
        'custom_str3' => 'getCustomStr3',
        'custom_str4' => 'getCustomStr4',
        'custom_str5' => 'getCustomStr5',
        'custom_dec1' => 'getCustomDec1',
        'custom_dec2' => 'getCustomDec2',
        'custom_int1' => 'getCustomInt1',
        'custom_int2' => 'getCustomInt2',
        'custom_date_time_utc1' => 'getCustomDateTimeUtc1'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OPERATION_INSERT = 'Insert';
    public const OPERATION_UPDATE = 'Update';
    public const OPERATION_DELETE = 'Delete';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOperationAllowableValues()
    {
        return [
            self::OPERATION_INSERT,
            self::OPERATION_UPDATE,
            self::OPERATION_DELETE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('operation', $data ?? [], null);
        $this->setIfExists('inventory_number', $data ?? [], null);
        $this->setIfExists('line_number', $data ?? [], null);
        $this->setIfExists('warehouse', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('uom', $data ?? [], null);
        $this->setIfExists('shipped_qty', $data ?? [], null);
        $this->setIfExists('custom_str1', $data ?? [], null);
        $this->setIfExists('custom_str2', $data ?? [], null);
        $this->setIfExists('custom_str3', $data ?? [], null);
        $this->setIfExists('custom_str4', $data ?? [], null);
        $this->setIfExists('custom_str5', $data ?? [], null);
        $this->setIfExists('custom_dec1', $data ?? [], null);
        $this->setIfExists('custom_dec2', $data ?? [], null);
        $this->setIfExists('custom_int1', $data ?? [], null);
        $this->setIfExists('custom_int2', $data ?? [], null);
        $this->setIfExists('custom_date_time_utc1', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getOperationAllowableValues();
        if (!is_null($this->container['operation']) && !in_array($this->container['operation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'operation', must be one of '%s'",
                $this->container['operation'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['inventory_number'] === null) {
            $invalidProperties[] = "'inventory_number' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets operation
     *
     * @return string|null
     */
    public function getOperation()
    {
        return $this->container['operation'];
    }

    /**
     * Sets operation
     *
     * @param string|null $operation operation
     *
     * @return self
     */
    public function setOperation($operation)
    {
        if (is_null($operation)) {
            throw new \InvalidArgumentException('non-nullable operation cannot be null');
        }
        $allowedValues = $this->getOperationAllowableValues();
        if (!in_array($operation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'operation', must be one of '%s'",
                    $operation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['operation'] = $operation;

        return $this;
    }

    /**
     * Gets inventory_number
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString
     */
    public function getInventoryNumber()
    {
        return $this->container['inventory_number'];
    }

    /**
     * Sets inventory_number
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString $inventory_number inventory_number
     *
     * @return self
     */
    public function setInventoryNumber($inventory_number)
    {
        if (is_null($inventory_number)) {
            throw new \InvalidArgumentException('non-nullable inventory_number cannot be null');
        }
        $this->container['inventory_number'] = $inventory_number;

        return $this;
    }

    /**
     * Gets line_number
     *
     * @return \OpenAPI\Client\Model\DtoValueOfInt32|null
     */
    public function getLineNumber()
    {
        return $this->container['line_number'];
    }

    /**
     * Sets line_number
     *
     * @param \OpenAPI\Client\Model\DtoValueOfInt32|null $line_number line_number
     *
     * @return self
     */
    public function setLineNumber($line_number)
    {
        if (is_null($line_number)) {
            throw new \InvalidArgumentException('non-nullable line_number cannot be null');
        }
        $this->container['line_number'] = $line_number;

        return $this;
    }

    /**
     * Gets warehouse
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getWarehouse()
    {
        return $this->container['warehouse'];
    }

    /**
     * Sets warehouse
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $warehouse warehouse
     *
     * @return self
     */
    public function setWarehouse($warehouse)
    {
        if (is_null($warehouse)) {
            throw new \InvalidArgumentException('non-nullable warehouse cannot be null');
        }
        $this->container['warehouse'] = $warehouse;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets uom
     *
     * @return \OpenAPI\Client\Model\DtoValueOfString|null
     */
    public function getUom()
    {
        return $this->container['uom'];
    }

    /**
     * Sets uom
     *
     * @param \OpenAPI\Client\Model\DtoValueOfString|null $uom uom
     *
     * @return self
     */
    public function setUom($uom)
    {
        if (is_null($uom)) {
            throw new \InvalidArgumentException('non-nullable uom cannot be null');
        }
        $this->container['uom'] = $uom;

        return $this;
    }

    /**
     * Gets shipped_qty
     *
     * @return \OpenAPI\Client\Model\DtoValueOfNullableOfDecimal|null
     */
    public function getShippedQty()
    {
        return $this->container['shipped_qty'];
    }

    /**
     * Sets shipped_qty
     *
     * @param \OpenAPI\Client\Model\DtoValueOfNullableOfDecimal|null $shipped_qty shipped_qty
     *
     * @return self
     */
    public function setShippedQty($shipped_qty)
    {
        if (is_null($shipped_qty)) {
            throw new \InvalidArgumentException('non-nullable shipped_qty cannot be null');
        }
        $this->container['shipped_qty'] = $shipped_qty;

        return $this;
    }

    /**
     * Gets custom_str1
     *
     * @return \OpenAPI\Client\Model\CustomStr1InShipmentDetailLineAddDto|null
     */
    public function getCustomStr1()
    {
        return $this->container['custom_str1'];
    }

    /**
     * Sets custom_str1
     *
     * @param \OpenAPI\Client\Model\CustomStr1InShipmentDetailLineAddDto|null $custom_str1 custom_str1
     *
     * @return self
     */
    public function setCustomStr1($custom_str1)
    {
        if (is_null($custom_str1)) {
            throw new \InvalidArgumentException('non-nullable custom_str1 cannot be null');
        }
        $this->container['custom_str1'] = $custom_str1;

        return $this;
    }

    /**
     * Gets custom_str2
     *
     * @return \OpenAPI\Client\Model\CustomStr2InShipmentDetailLineAddDto|null
     */
    public function getCustomStr2()
    {
        return $this->container['custom_str2'];
    }

    /**
     * Sets custom_str2
     *
     * @param \OpenAPI\Client\Model\CustomStr2InShipmentDetailLineAddDto|null $custom_str2 custom_str2
     *
     * @return self
     */
    public function setCustomStr2($custom_str2)
    {
        if (is_null($custom_str2)) {
            throw new \InvalidArgumentException('non-nullable custom_str2 cannot be null');
        }
        $this->container['custom_str2'] = $custom_str2;

        return $this;
    }

    /**
     * Gets custom_str3
     *
     * @return \OpenAPI\Client\Model\CustomStr3InShipmentDetailLineAddDto|null
     */
    public function getCustomStr3()
    {
        return $this->container['custom_str3'];
    }

    /**
     * Sets custom_str3
     *
     * @param \OpenAPI\Client\Model\CustomStr3InShipmentDetailLineAddDto|null $custom_str3 custom_str3
     *
     * @return self
     */
    public function setCustomStr3($custom_str3)
    {
        if (is_null($custom_str3)) {
            throw new \InvalidArgumentException('non-nullable custom_str3 cannot be null');
        }
        $this->container['custom_str3'] = $custom_str3;

        return $this;
    }

    /**
     * Gets custom_str4
     *
     * @return \OpenAPI\Client\Model\CustomStr4InShipmentDetailLineAddDto|null
     */
    public function getCustomStr4()
    {
        return $this->container['custom_str4'];
    }

    /**
     * Sets custom_str4
     *
     * @param \OpenAPI\Client\Model\CustomStr4InShipmentDetailLineAddDto|null $custom_str4 custom_str4
     *
     * @return self
     */
    public function setCustomStr4($custom_str4)
    {
        if (is_null($custom_str4)) {
            throw new \InvalidArgumentException('non-nullable custom_str4 cannot be null');
        }
        $this->container['custom_str4'] = $custom_str4;

        return $this;
    }

    /**
     * Gets custom_str5
     *
     * @return \OpenAPI\Client\Model\CustomStr5InShipmentDetailLineAddDto|null
     */
    public function getCustomStr5()
    {
        return $this->container['custom_str5'];
    }

    /**
     * Sets custom_str5
     *
     * @param \OpenAPI\Client\Model\CustomStr5InShipmentDetailLineAddDto|null $custom_str5 custom_str5
     *
     * @return self
     */
    public function setCustomStr5($custom_str5)
    {
        if (is_null($custom_str5)) {
            throw new \InvalidArgumentException('non-nullable custom_str5 cannot be null');
        }
        $this->container['custom_str5'] = $custom_str5;

        return $this;
    }

    /**
     * Gets custom_dec1
     *
     * @return \OpenAPI\Client\Model\CustomDec1InShipmentDetailLineAddDto|null
     */
    public function getCustomDec1()
    {
        return $this->container['custom_dec1'];
    }

    /**
     * Sets custom_dec1
     *
     * @param \OpenAPI\Client\Model\CustomDec1InShipmentDetailLineAddDto|null $custom_dec1 custom_dec1
     *
     * @return self
     */
    public function setCustomDec1($custom_dec1)
    {
        if (is_null($custom_dec1)) {
            throw new \InvalidArgumentException('non-nullable custom_dec1 cannot be null');
        }
        $this->container['custom_dec1'] = $custom_dec1;

        return $this;
    }

    /**
     * Gets custom_dec2
     *
     * @return \OpenAPI\Client\Model\CustomDec2InShipmentDetailLineAddDto|null
     */
    public function getCustomDec2()
    {
        return $this->container['custom_dec2'];
    }

    /**
     * Sets custom_dec2
     *
     * @param \OpenAPI\Client\Model\CustomDec2InShipmentDetailLineAddDto|null $custom_dec2 custom_dec2
     *
     * @return self
     */
    public function setCustomDec2($custom_dec2)
    {
        if (is_null($custom_dec2)) {
            throw new \InvalidArgumentException('non-nullable custom_dec2 cannot be null');
        }
        $this->container['custom_dec2'] = $custom_dec2;

        return $this;
    }

    /**
     * Gets custom_int1
     *
     * @return \OpenAPI\Client\Model\CustomInt1InShipmentDetailLineAddDto|null
     */
    public function getCustomInt1()
    {
        return $this->container['custom_int1'];
    }

    /**
     * Sets custom_int1
     *
     * @param \OpenAPI\Client\Model\CustomInt1InShipmentDetailLineAddDto|null $custom_int1 custom_int1
     *
     * @return self
     */
    public function setCustomInt1($custom_int1)
    {
        if (is_null($custom_int1)) {
            throw new \InvalidArgumentException('non-nullable custom_int1 cannot be null');
        }
        $this->container['custom_int1'] = $custom_int1;

        return $this;
    }

    /**
     * Gets custom_int2
     *
     * @return \OpenAPI\Client\Model\CustomInt2InShipmentDetailLineAddDto|null
     */
    public function getCustomInt2()
    {
        return $this->container['custom_int2'];
    }

    /**
     * Sets custom_int2
     *
     * @param \OpenAPI\Client\Model\CustomInt2InShipmentDetailLineAddDto|null $custom_int2 custom_int2
     *
     * @return self
     */
    public function setCustomInt2($custom_int2)
    {
        if (is_null($custom_int2)) {
            throw new \InvalidArgumentException('non-nullable custom_int2 cannot be null');
        }
        $this->container['custom_int2'] = $custom_int2;

        return $this;
    }

    /**
     * Gets custom_date_time_utc1
     *
     * @return \OpenAPI\Client\Model\CustomDateTimeUTC1InShipmentDetailLineAddDto|null
     */
    public function getCustomDateTimeUtc1()
    {
        return $this->container['custom_date_time_utc1'];
    }

    /**
     * Sets custom_date_time_utc1
     *
     * @param \OpenAPI\Client\Model\CustomDateTimeUTC1InShipmentDetailLineAddDto|null $custom_date_time_utc1 custom_date_time_utc1
     *
     * @return self
     */
    public function setCustomDateTimeUtc1($custom_date_time_utc1)
    {
        if (is_null($custom_date_time_utc1)) {
            throw new \InvalidArgumentException('non-nullable custom_date_time_utc1 cannot be null');
        }
        $this->container['custom_date_time_utc1'] = $custom_date_time_utc1;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


