<?php
/**
 * TaskQueryParameters
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TaskQueryParameters Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TaskQueryParameters implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TaskQueryParameters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'project_id' => 'string',
        'public_id' => 'string',
        'project_internal_id' => 'int',
        'description' => 'string',
        'task_cd' => 'string',
        'task_cd_desc' => 'string',
        'status' => 'string',
        'expand_attribute' => 'bool',
        'visible_in_ap' => 'bool',
        'visible_in_ar' => 'bool',
        'visible_in_ca' => 'bool',
        'visible_in_cr' => 'bool',
        'visible_in_ea' => 'bool',
        'visible_in_gl' => 'bool',
        'visible_in_in' => 'bool',
        'visible_in_po' => 'bool',
        'visible_in_so' => 'bool',
        'visible_in_ta' => 'bool',
        'restricted_employee' => 'string',
        'restricted_user' => 'int',
        'greater_than_value' => 'string',
        'number_to_read' => 'int',
        'skip_records' => 'int',
        'last_modified_date_time' => 'string',
        'last_modified_date_time_condition' => 'string',
        'created_date_time' => 'string',
        'created_date_time_condition' => 'string',
        'page_number' => 'int',
        'page_size' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'project_id' => null,
        'public_id' => 'uuid',
        'project_internal_id' => 'int32',
        'description' => null,
        'task_cd' => null,
        'task_cd_desc' => null,
        'status' => null,
        'expand_attribute' => null,
        'visible_in_ap' => null,
        'visible_in_ar' => null,
        'visible_in_ca' => null,
        'visible_in_cr' => null,
        'visible_in_ea' => null,
        'visible_in_gl' => null,
        'visible_in_in' => null,
        'visible_in_po' => null,
        'visible_in_so' => null,
        'visible_in_ta' => null,
        'restricted_employee' => null,
        'restricted_user' => 'int64',
        'greater_than_value' => null,
        'number_to_read' => 'int32',
        'skip_records' => 'int32',
        'last_modified_date_time' => null,
        'last_modified_date_time_condition' => null,
        'created_date_time' => null,
        'created_date_time_condition' => null,
        'page_number' => 'int32',
        'page_size' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'project_id' => false,
        'public_id' => false,
        'project_internal_id' => false,
        'description' => false,
        'task_cd' => false,
        'task_cd_desc' => false,
        'status' => false,
        'expand_attribute' => false,
        'visible_in_ap' => false,
        'visible_in_ar' => false,
        'visible_in_ca' => false,
        'visible_in_cr' => false,
        'visible_in_ea' => false,
        'visible_in_gl' => false,
        'visible_in_in' => false,
        'visible_in_po' => false,
        'visible_in_so' => false,
        'visible_in_ta' => false,
        'restricted_employee' => false,
        'restricted_user' => false,
        'greater_than_value' => false,
        'number_to_read' => false,
        'skip_records' => false,
        'last_modified_date_time' => false,
        'last_modified_date_time_condition' => false,
        'created_date_time' => false,
        'created_date_time_condition' => false,
        'page_number' => false,
        'page_size' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'project_id' => 'projectId',
        'public_id' => 'publicId',
        'project_internal_id' => 'projectInternalId',
        'description' => 'description',
        'task_cd' => 'taskCd',
        'task_cd_desc' => 'taskCdDesc',
        'status' => 'status',
        'expand_attribute' => 'expandAttribute',
        'visible_in_ap' => 'visibleInAp',
        'visible_in_ar' => 'visibleInAr',
        'visible_in_ca' => 'visibleInCa',
        'visible_in_cr' => 'visibleInCr',
        'visible_in_ea' => 'visibleInEa',
        'visible_in_gl' => 'visibleInGl',
        'visible_in_in' => 'visibleInIn',
        'visible_in_po' => 'visibleInPo',
        'visible_in_so' => 'visibleInSo',
        'visible_in_ta' => 'visibleInTa',
        'restricted_employee' => 'restrictedEmployee',
        'restricted_user' => 'restrictedUser',
        'greater_than_value' => 'greaterThanValue',
        'number_to_read' => 'numberToRead',
        'skip_records' => 'skipRecords',
        'last_modified_date_time' => 'lastModifiedDateTime',
        'last_modified_date_time_condition' => 'lastModifiedDateTimeCondition',
        'created_date_time' => 'createdDateTime',
        'created_date_time_condition' => 'createdDateTimeCondition',
        'page_number' => 'pageNumber',
        'page_size' => 'pageSize'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'project_id' => 'setProjectId',
        'public_id' => 'setPublicId',
        'project_internal_id' => 'setProjectInternalId',
        'description' => 'setDescription',
        'task_cd' => 'setTaskCd',
        'task_cd_desc' => 'setTaskCdDesc',
        'status' => 'setStatus',
        'expand_attribute' => 'setExpandAttribute',
        'visible_in_ap' => 'setVisibleInAp',
        'visible_in_ar' => 'setVisibleInAr',
        'visible_in_ca' => 'setVisibleInCa',
        'visible_in_cr' => 'setVisibleInCr',
        'visible_in_ea' => 'setVisibleInEa',
        'visible_in_gl' => 'setVisibleInGl',
        'visible_in_in' => 'setVisibleInIn',
        'visible_in_po' => 'setVisibleInPo',
        'visible_in_so' => 'setVisibleInSo',
        'visible_in_ta' => 'setVisibleInTa',
        'restricted_employee' => 'setRestrictedEmployee',
        'restricted_user' => 'setRestrictedUser',
        'greater_than_value' => 'setGreaterThanValue',
        'number_to_read' => 'setNumberToRead',
        'skip_records' => 'setSkipRecords',
        'last_modified_date_time' => 'setLastModifiedDateTime',
        'last_modified_date_time_condition' => 'setLastModifiedDateTimeCondition',
        'created_date_time' => 'setCreatedDateTime',
        'created_date_time_condition' => 'setCreatedDateTimeCondition',
        'page_number' => 'setPageNumber',
        'page_size' => 'setPageSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'project_id' => 'getProjectId',
        'public_id' => 'getPublicId',
        'project_internal_id' => 'getProjectInternalId',
        'description' => 'getDescription',
        'task_cd' => 'getTaskCd',
        'task_cd_desc' => 'getTaskCdDesc',
        'status' => 'getStatus',
        'expand_attribute' => 'getExpandAttribute',
        'visible_in_ap' => 'getVisibleInAp',
        'visible_in_ar' => 'getVisibleInAr',
        'visible_in_ca' => 'getVisibleInCa',
        'visible_in_cr' => 'getVisibleInCr',
        'visible_in_ea' => 'getVisibleInEa',
        'visible_in_gl' => 'getVisibleInGl',
        'visible_in_in' => 'getVisibleInIn',
        'visible_in_po' => 'getVisibleInPo',
        'visible_in_so' => 'getVisibleInSo',
        'visible_in_ta' => 'getVisibleInTa',
        'restricted_employee' => 'getRestrictedEmployee',
        'restricted_user' => 'getRestrictedUser',
        'greater_than_value' => 'getGreaterThanValue',
        'number_to_read' => 'getNumberToRead',
        'skip_records' => 'getSkipRecords',
        'last_modified_date_time' => 'getLastModifiedDateTime',
        'last_modified_date_time_condition' => 'getLastModifiedDateTimeCondition',
        'created_date_time' => 'getCreatedDateTime',
        'created_date_time_condition' => 'getCreatedDateTimeCondition',
        'page_number' => 'getPageNumber',
        'page_size' => 'getPageSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_PLANNED = 'Planned';
    public const STATUS_ACTIVE = 'Active';
    public const STATUS_CANCELLED = 'Cancelled';
    public const STATUS_CANCELED = 'Canceled';
    public const STATUS_COMPLETED = 'Completed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PLANNED,
            self::STATUS_ACTIVE,
            self::STATUS_CANCELLED,
            self::STATUS_CANCELED,
            self::STATUS_COMPLETED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('public_id', $data ?? [], null);
        $this->setIfExists('project_internal_id', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('task_cd', $data ?? [], null);
        $this->setIfExists('task_cd_desc', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('expand_attribute', $data ?? [], null);
        $this->setIfExists('visible_in_ap', $data ?? [], null);
        $this->setIfExists('visible_in_ar', $data ?? [], null);
        $this->setIfExists('visible_in_ca', $data ?? [], null);
        $this->setIfExists('visible_in_cr', $data ?? [], null);
        $this->setIfExists('visible_in_ea', $data ?? [], null);
        $this->setIfExists('visible_in_gl', $data ?? [], null);
        $this->setIfExists('visible_in_in', $data ?? [], null);
        $this->setIfExists('visible_in_po', $data ?? [], null);
        $this->setIfExists('visible_in_so', $data ?? [], null);
        $this->setIfExists('visible_in_ta', $data ?? [], null);
        $this->setIfExists('restricted_employee', $data ?? [], null);
        $this->setIfExists('restricted_user', $data ?? [], null);
        $this->setIfExists('greater_than_value', $data ?? [], null);
        $this->setIfExists('number_to_read', $data ?? [], null);
        $this->setIfExists('skip_records', $data ?? [], null);
        $this->setIfExists('last_modified_date_time', $data ?? [], null);
        $this->setIfExists('last_modified_date_time_condition', $data ?? [], null);
        $this->setIfExists('created_date_time', $data ?? [], null);
        $this->setIfExists('created_date_time_condition', $data ?? [], null);
        $this->setIfExists('page_number', $data ?? [], null);
        $this->setIfExists('page_size', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id Identifies the Project
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets public_id
     *
     * @return string|null
     */
    public function getPublicId()
    {
        return $this->container['public_id'];
    }

    /**
     * Sets public_id
     *
     * @param string|null $public_id Identifies the project by publicId
     *
     * @return self
     */
    public function setPublicId($public_id)
    {
        if (is_null($public_id)) {
            throw new \InvalidArgumentException('non-nullable public_id cannot be null');
        }
        $this->container['public_id'] = $public_id;

        return $this;
    }

    /**
     * Gets project_internal_id
     *
     * @return int|null
     */
    public function getProjectInternalId()
    {
        return $this->container['project_internal_id'];
    }

    /**
     * Sets project_internal_id
     *
     * @param int|null $project_internal_id Identifies the project by internal id
     *
     * @return self
     */
    public function setProjectInternalId($project_internal_id)
    {
        if (is_null($project_internal_id)) {
            throw new \InvalidArgumentException('non-nullable project_internal_id cannot be null');
        }
        $this->container['project_internal_id'] = $project_internal_id;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Identifies the Project task description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets task_cd
     *
     * @return string|null
     */
    public function getTaskCd()
    {
        return $this->container['task_cd'];
    }

    /**
     * Sets task_cd
     *
     * @param string|null $task_cd Identifies the Project task ID
     *
     * @return self
     */
    public function setTaskCd($task_cd)
    {
        if (is_null($task_cd)) {
            throw new \InvalidArgumentException('non-nullable task_cd cannot be null');
        }
        $this->container['task_cd'] = $task_cd;

        return $this;
    }

    /**
     * Gets task_cd_desc
     *
     * @return string|null
     */
    public function getTaskCdDesc()
    {
        return $this->container['task_cd_desc'];
    }

    /**
     * Sets task_cd_desc
     *
     * @param string|null $task_cd_desc Identifies the Project task ID and description
     *
     * @return self
     */
    public function setTaskCdDesc($task_cd_desc)
    {
        if (is_null($task_cd_desc)) {
            throw new \InvalidArgumentException('non-nullable task_cd_desc cannot be null');
        }
        $this->container['task_cd_desc'] = $task_cd_desc;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The status of the document.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets expand_attribute
     *
     * @return bool|null
     */
    public function getExpandAttribute()
    {
        return $this->container['expand_attribute'];
    }

    /**
     * Sets expand_attribute
     *
     * @param bool|null $expand_attribute Expands project atributes
     *
     * @return self
     */
    public function setExpandAttribute($expand_attribute)
    {
        if (is_null($expand_attribute)) {
            throw new \InvalidArgumentException('non-nullable expand_attribute cannot be null');
        }
        $this->container['expand_attribute'] = $expand_attribute;

        return $this;
    }

    /**
     * Gets visible_in_ap
     *
     * @return bool|null
     */
    public function getVisibleInAp()
    {
        return $this->container['visible_in_ap'];
    }

    /**
     * Sets visible_in_ap
     *
     * @param bool|null $visible_in_ap If the project task is visible in the Supplier ledger
     *
     * @return self
     */
    public function setVisibleInAp($visible_in_ap)
    {
        if (is_null($visible_in_ap)) {
            throw new \InvalidArgumentException('non-nullable visible_in_ap cannot be null');
        }
        $this->container['visible_in_ap'] = $visible_in_ap;

        return $this;
    }

    /**
     * Gets visible_in_ar
     *
     * @return bool|null
     */
    public function getVisibleInAr()
    {
        return $this->container['visible_in_ar'];
    }

    /**
     * Sets visible_in_ar
     *
     * @param bool|null $visible_in_ar If the project task is visible in the Customer ledger
     *
     * @return self
     */
    public function setVisibleInAr($visible_in_ar)
    {
        if (is_null($visible_in_ar)) {
            throw new \InvalidArgumentException('non-nullable visible_in_ar cannot be null');
        }
        $this->container['visible_in_ar'] = $visible_in_ar;

        return $this;
    }

    /**
     * Gets visible_in_ca
     *
     * @return bool|null
     */
    public function getVisibleInCa()
    {
        return $this->container['visible_in_ca'];
    }

    /**
     * Sets visible_in_ca
     *
     * @param bool|null $visible_in_ca If the project task is visible in the Cash management workspace
     *
     * @return self
     */
    public function setVisibleInCa($visible_in_ca)
    {
        if (is_null($visible_in_ca)) {
            throw new \InvalidArgumentException('non-nullable visible_in_ca cannot be null');
        }
        $this->container['visible_in_ca'] = $visible_in_ca;

        return $this;
    }

    /**
     * Gets visible_in_cr
     *
     * @return bool|null
     */
    public function getVisibleInCr()
    {
        return $this->container['visible_in_cr'];
    }

    /**
     * Sets visible_in_cr
     *
     * @param bool|null $visible_in_cr If the project task is visible in the CRM workspace
     *
     * @return self
     */
    public function setVisibleInCr($visible_in_cr)
    {
        if (is_null($visible_in_cr)) {
            throw new \InvalidArgumentException('non-nullable visible_in_cr cannot be null');
        }
        $this->container['visible_in_cr'] = $visible_in_cr;

        return $this;
    }

    /**
     * Gets visible_in_ea
     *
     * @return bool|null
     */
    public function getVisibleInEa()
    {
        return $this->container['visible_in_ea'];
    }

    /**
     * Sets visible_in_ea
     *
     * @param bool|null $visible_in_ea If the project task is visible in the Expense workspace
     *
     * @return self
     */
    public function setVisibleInEa($visible_in_ea)
    {
        if (is_null($visible_in_ea)) {
            throw new \InvalidArgumentException('non-nullable visible_in_ea cannot be null');
        }
        $this->container['visible_in_ea'] = $visible_in_ea;

        return $this;
    }

    /**
     * Gets visible_in_gl
     *
     * @return bool|null
     */
    public function getVisibleInGl()
    {
        return $this->container['visible_in_gl'];
    }

    /**
     * Sets visible_in_gl
     *
     * @param bool|null $visible_in_gl If the project task is visible in the General ledger workspace
     *
     * @return self
     */
    public function setVisibleInGl($visible_in_gl)
    {
        if (is_null($visible_in_gl)) {
            throw new \InvalidArgumentException('non-nullable visible_in_gl cannot be null');
        }
        $this->container['visible_in_gl'] = $visible_in_gl;

        return $this;
    }

    /**
     * Gets visible_in_in
     *
     * @return bool|null
     */
    public function getVisibleInIn()
    {
        return $this->container['visible_in_in'];
    }

    /**
     * Sets visible_in_in
     *
     * @param bool|null $visible_in_in If the project task is visible in the Inventory workspace
     *
     * @return self
     */
    public function setVisibleInIn($visible_in_in)
    {
        if (is_null($visible_in_in)) {
            throw new \InvalidArgumentException('non-nullable visible_in_in cannot be null');
        }
        $this->container['visible_in_in'] = $visible_in_in;

        return $this;
    }

    /**
     * Gets visible_in_po
     *
     * @return bool|null
     */
    public function getVisibleInPo()
    {
        return $this->container['visible_in_po'];
    }

    /**
     * Sets visible_in_po
     *
     * @param bool|null $visible_in_po If the project task is visible in the Purchases workspace
     *
     * @return self
     */
    public function setVisibleInPo($visible_in_po)
    {
        if (is_null($visible_in_po)) {
            throw new \InvalidArgumentException('non-nullable visible_in_po cannot be null');
        }
        $this->container['visible_in_po'] = $visible_in_po;

        return $this;
    }

    /**
     * Gets visible_in_so
     *
     * @return bool|null
     */
    public function getVisibleInSo()
    {
        return $this->container['visible_in_so'];
    }

    /**
     * Sets visible_in_so
     *
     * @param bool|null $visible_in_so If the project task is visible in the Sales workspace
     *
     * @return self
     */
    public function setVisibleInSo($visible_in_so)
    {
        if (is_null($visible_in_so)) {
            throw new \InvalidArgumentException('non-nullable visible_in_so cannot be null');
        }
        $this->container['visible_in_so'] = $visible_in_so;

        return $this;
    }

    /**
     * Gets visible_in_ta
     *
     * @return bool|null
     */
    public function getVisibleInTa()
    {
        return $this->container['visible_in_ta'];
    }

    /**
     * Sets visible_in_ta
     *
     * @param bool|null $visible_in_ta If the project task is visible in the Time entities workspace
     *
     * @return self
     */
    public function setVisibleInTa($visible_in_ta)
    {
        if (is_null($visible_in_ta)) {
            throw new \InvalidArgumentException('non-nullable visible_in_ta cannot be null');
        }
        $this->container['visible_in_ta'] = $visible_in_ta;

        return $this;
    }

    /**
     * Gets restricted_employee
     *
     * @return string|null
     */
    public function getRestrictedEmployee()
    {
        return $this->container['restricted_employee'];
    }

    /**
     * Sets restricted_employee
     *
     * @param string|null $restricted_employee Id of the employee where access restrictions apply
     *
     * @return self
     */
    public function setRestrictedEmployee($restricted_employee)
    {
        if (is_null($restricted_employee)) {
            throw new \InvalidArgumentException('non-nullable restricted_employee cannot be null');
        }
        $this->container['restricted_employee'] = $restricted_employee;

        return $this;
    }

    /**
     * Gets restricted_user
     *
     * @return int|null
     */
    public function getRestrictedUser()
    {
        return $this->container['restricted_user'];
    }

    /**
     * Sets restricted_user
     *
     * @param int|null $restricted_user Id of the Odp User where access restrictions apply
     *
     * @return self
     */
    public function setRestrictedUser($restricted_user)
    {
        if (is_null($restricted_user)) {
            throw new \InvalidArgumentException('non-nullable restricted_user cannot be null');
        }
        $this->container['restricted_user'] = $restricted_user;

        return $this;
    }

    /**
     * Gets greater_than_value
     *
     * @return string|null
     */
    public function getGreaterThanValue()
    {
        return $this->container['greater_than_value'];
    }

    /**
     * Sets greater_than_value
     *
     * @param string|null $greater_than_value Greater than value. The item which is the object for this, varies from API to API.
     *
     * @return self
     */
    public function setGreaterThanValue($greater_than_value)
    {
        if (is_null($greater_than_value)) {
            throw new \InvalidArgumentException('non-nullable greater_than_value cannot be null');
        }
        $this->container['greater_than_value'] = $greater_than_value;

        return $this;
    }

    /**
     * Gets number_to_read
     *
     * @return int|null
     */
    public function getNumberToRead()
    {
        return $this->container['number_to_read'];
    }

    /**
     * Sets number_to_read
     *
     * @param int|null $number_to_read This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     *
     * @return self
     */
    public function setNumberToRead($number_to_read)
    {
        if (is_null($number_to_read)) {
            throw new \InvalidArgumentException('non-nullable number_to_read cannot be null');
        }
        $this->container['number_to_read'] = $number_to_read;

        return $this;
    }

    /**
     * Gets skip_records
     *
     * @return int|null
     */
    public function getSkipRecords()
    {
        return $this->container['skip_records'];
    }

    /**
     * Sets skip_records
     *
     * @param int|null $skip_records This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     *
     * @return self
     */
    public function setSkipRecords($skip_records)
    {
        if (is_null($skip_records)) {
            throw new \InvalidArgumentException('non-nullable skip_records cannot be null');
        }
        $this->container['skip_records'] = $skip_records;

        return $this;
    }

    /**
     * Gets last_modified_date_time
     *
     * @return string|null
     */
    public function getLastModifiedDateTime()
    {
        return $this->container['last_modified_date_time'];
    }

    /**
     * Sets last_modified_date_time
     *
     * @param string|null $last_modified_date_time This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.    Accepted format:  * ```yyyy-MM-dd```  * ```yyyy-MM-dd HH:mm:ss```  * ```yyyy-MM-dd HH:mm:ss.FFF```  * ```yyyy-MM-ddTHH:mm:ss```  * ```yyyy-MM-ddTHH:mm:ss.FFF```    _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     *
     * @return self
     */
    public function setLastModifiedDateTime($last_modified_date_time)
    {
        if (is_null($last_modified_date_time)) {
            throw new \InvalidArgumentException('non-nullable last_modified_date_time cannot be null');
        }
        $this->container['last_modified_date_time'] = $last_modified_date_time;

        return $this;
    }

    /**
     * Gets last_modified_date_time_condition
     *
     * @return string|null
     */
    public function getLastModifiedDateTimeCondition()
    {
        return $this->container['last_modified_date_time_condition'];
    }

    /**
     * Sets last_modified_date_time_condition
     *
     * @param string|null $last_modified_date_time_condition This value represents the condition to be applied when retrieving records.    Accepted values (without the single quotes):  * '&gt;' for greater than  * '&lt;' for less than  * '&gt;=' for greater than or equal  * '&lt;=' for less than or equal    _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     *
     * @return self
     */
    public function setLastModifiedDateTimeCondition($last_modified_date_time_condition)
    {
        if (is_null($last_modified_date_time_condition)) {
            throw new \InvalidArgumentException('non-nullable last_modified_date_time_condition cannot be null');
        }
        $this->container['last_modified_date_time_condition'] = $last_modified_date_time_condition;

        return $this;
    }

    /**
     * Gets created_date_time
     *
     * @return string|null
     */
    public function getCreatedDateTime()
    {
        return $this->container['created_date_time'];
    }

    /**
     * Sets created_date_time
     *
     * @param string|null $created_date_time Creation date and time.
     *
     * @return self
     */
    public function setCreatedDateTime($created_date_time)
    {
        if (is_null($created_date_time)) {
            throw new \InvalidArgumentException('non-nullable created_date_time cannot be null');
        }
        $this->container['created_date_time'] = $created_date_time;

        return $this;
    }

    /**
     * Gets created_date_time_condition
     *
     * @return string|null
     */
    public function getCreatedDateTimeCondition()
    {
        return $this->container['created_date_time_condition'];
    }

    /**
     * Sets created_date_time_condition
     *
     * @param string|null $created_date_time_condition System-retrieved information for state/condition
     *
     * @return self
     */
    public function setCreatedDateTimeCondition($created_date_time_condition)
    {
        if (is_null($created_date_time_condition)) {
            throw new \InvalidArgumentException('non-nullable created_date_time_condition cannot be null');
        }
        $this->container['created_date_time_condition'] = $created_date_time_condition;

        return $this;
    }

    /**
     * Gets page_number
     *
     * @return int|null
     */
    public function getPageNumber()
    {
        return $this->container['page_number'];
    }

    /**
     * Sets page_number
     *
     * @param int|null $page_number Pagination parameter. Page number.
     *
     * @return self
     */
    public function setPageNumber($page_number)
    {
        if (is_null($page_number)) {
            throw new \InvalidArgumentException('non-nullable page_number cannot be null');
        }
        $this->container['page_number'] = $page_number;

        return $this;
    }

    /**
     * Gets page_size
     *
     * @return int|null
     */
    public function getPageSize()
    {
        return $this->container['page_size'];
    }

    /**
     * Sets page_size
     *
     * @param int|null $page_size Pagination parameter. Number of items to be collected.  Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.  If requested page size is greater than allowed max page size, request will be limited to max page size.
     *
     * @return self
     */
    public function setPageSize($page_size)
    {
        if (is_null($page_size)) {
            throw new \InvalidArgumentException('non-nullable page_size cannot be null');
        }
        $this->container['page_size'] = $page_size;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


