<?php
/**
 * CustomerContractApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerContractApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerContractApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for customerContractActivateContractBycontractId
     *
     * Activate contract operation.
     *
     */
    public function testCustomerContractActivateContractBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractActivateUpgradeBycontractId
     *
     * Activate upgrade contract operation.
     *
     */
    public function testCustomerContractActivateUpgradeBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractCreateCustomerContract
     *
     * Create a CustomerContract.
     *
     */
    public function testCustomerContractCreateCustomerContract()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractGetAll
     *
     * Get a range of Customer Contracts, a filter needs to be specified - ScreenId=CT301000.
     *
     */
    public function testCustomerContractGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractGetCustomerContractBycontractId
     *
     * Get a specific Customer Contract.
     *
     */
    public function testCustomerContractGetCustomerContractBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractGetCustomerContractDetailsBycontractId
     *
     * Get a specific Customer Contract Details.
     *
     */
    public function testCustomerContractGetCustomerContractDetailsBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractGetCustomerContractRecurringSummaryBycontractId
     *
     * Get a specific Customer Contract Recurring Summary.
     *
     */
    public function testCustomerContractGetCustomerContractRecurringSummaryBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractGetCustomerContractSummaryBycontractId
     *
     * Get a specific Customer Contract Summary.
     *
     */
    public function testCustomerContractGetCustomerContractSummaryBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractPutBycontractId
     *
     * Update a specific CustomerContract.
     *
     */
    public function testCustomerContractPutBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractSetupAndActivateContractBycontractId
     *
     * Setup and Activate contract operation.
     *
     */
    public function testCustomerContractSetupAndActivateContractBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractSetupContractBycontractId
     *
     * Setup contract operation.
     *
     */
    public function testCustomerContractSetupContractBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractTerminateContractBycontractId
     *
     * Terminate contract operation.
     *
     */
    public function testCustomerContractTerminateContractBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerContractUpgradeContractBycontractId
     *
     * Upgrade contract operation.
     *
     */
    public function testCustomerContractUpgradeContractBycontractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
