<?php
/**
 * PurchaseOrderApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PurchaseOrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseOrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for purchaseOrderCreatePurchaseReceiptFromPurchaseOrderBypurchaseorderNbr
     *
     * Creates a purchase receipt from an existing purchase order..
     *
     */
    public function testPurchaseOrderCreatePurchaseReceiptFromPurchaseOrderBypurchaseorderNbr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderGetAllOrder
     *
     * Get a range of Purchase Order - ScreenId=PO301000  Request page size must be lower or equal to the allowed max page size which is returned as part of the metadata information.  If requested page size is greater than allowed max page size, request will be limited to max page size  Change log:  2020-May:Added forced pagination.
     *
     */
    public function testPurchaseOrderGetAllOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderGetOrderBypurchaseOrderNumber
     *
     * Get a specific Purchase Order.
     *
     */
    public function testPurchaseOrderGetOrderBypurchaseOrderNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderPost
     *
     * Create a Purchase Order.
     *
     */
    public function testPurchaseOrderPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderPutBypurchaseOrderNumber
     *
     * Update a Purchase Order.
     *
     */
    public function testPurchaseOrderPutBypurchaseOrderNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
