<?php
/**
 * PurchaseReceiptBasicApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Visma.net ERP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PurchaseReceiptBasicApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseReceiptBasicApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for purchaseReceiptBasicGetAllReceiptBasic
     *
     * Get a range with purchase receipts, ScreenId=PO302000  Please use a page size lower or equal to the allowed max page size which is 500.
     *
     */
    public function testPurchaseReceiptBasicGetAllReceiptBasic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseReceiptBasicGetPurchaseReceiptBasicByreceiptNumber
     *
     * Get a specific Purchase Receipt.
     *
     */
    public function testPurchaseReceiptBasicGetPurchaseReceiptBasicByreceiptNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseReceiptBasicPost
     *
     * Create a Purchase Receipt.
     *
     */
    public function testPurchaseReceiptBasicPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseReceiptBasicPutByreceiptNumber
     *
     * Update a specific Purchase Receipt.
     *
     */
    public function testPurchaseReceiptBasicPutByreceiptNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseReceiptBasicReleaseInvoiceByreceiptNumber
     *
     * Release purchase receipt operation.
     *
     */
    public function testPurchaseReceiptBasicReleaseInvoiceByreceiptNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
